### ISSUE TITLE
Integrate the RINEX crate to the community

### ISSUE THREAD

**Issue by gwbres** [georust/geo#1016]
Hello @urschrei, @lnicola,

Lars and I have discussed about the future of our [RINEX crate](https://github.com/gwbres/rinex) and decided the best scenario would be to join a broader community.  Having said that, `georust` is the one that came to mind naturally.

The topic was discussed a little bit on Github and also on Discord.

This crate is a RINEX file parser and comprises a set of tools that are built around it. 
It supports already quite a lot of formats, and several remain to be supported.    
RINEX is simple in its description but complex due to all form / variations it may have, and also for its data content.

Since v0.2/v0.3 we came up with a nice framework to at least support multiple RINEX formats.   
At this point we may havecrossed the point where this tool is the only one to combine standard RINEX like Observation/Navigation, and exotic RINEX like Clock / Ionosphere maps.  
Also there aren't many tools out there that truly support RINEX V4 which is the latest standard.
RINEX files have a tendency to be heavy, so a compression algorithm was developed many years ago, which we also support since v0.5/v0.6.

There are interesting opportunities regarding this set of tools.

- several tools exist and usually require people to combine all of them to achieve one goal.
Our set of tool may simplify the job pipeline of people working on these topics.
For example you can decompress, extract, analyze and process, reformat in a single environment.
- most of these tools are private software
- most of them are old and probably no longer maintained. Our framework would bring an interesting modern approach
- for example, we're already a consistent alternative to `crx2rnx` which was written in C 15+ years ago, and is the only option on the market that I'm aware of, to decompress a rinex file

But for this, we need the tool to spread to the community.

This framework still has quite a lot to achieve and potential developments:
- provide more processing algorithms (GNSS signal analysis, precise positioning, precise timing, ionosphere / troposphere analysis etc..). Here I'm facing the problem I'm more familiar with Timing related applications. I learned a bit about GNSS with all of this. But these are really the work subjets of GNSS engineers or atmospheric science
- gain more stability and robustness. We achieved decent results with CI/CD
- truly support RINEX in all its variations. If we take RINEXV4 for example, the topics get more & more complex and it naturally takes deeper knowledge and longer time to be robust
- be a credible alternative to `teqc`

Well, having said of all that, and if you  guys are willing to have us on board, we'd be happy to continue this journey and have you help us reach a broader audience and have more people involved in its maintenance. I have no experience in Github organizations, so you would have to guide on the steps to take.

Lars and I don't want to give up on this topic. The pending v0.9 sees a first visualization of Ionosphere maps and a nicer web-based analysis report. The plan is to release a V1.0 once RINEXV4 is correctly supported for all navigation frames, which are the most complex

**Comment by urschrei** [comment]
Hello! Apologies for the delay in responding to this. The crate is clearly high-quality, and you have a long and exciting feature roadmap – we (the GeoRust community) would be delighted to have you become a formal part of the ecosystem. I say "ecosystem" as Georust is made up of both loosely and tightly-coupled groups of people, with the smallest feasible amount of structure that allows people to work together, provide crate maintenance when it's necessary, and ensure that "georust" exists as a recognisable entity.

There are few requirements for crate authors, and you already use the Rust CoC. So next steps would be:

1. Transfer the repo to the georust organisation, while retaining your existing repo admins
2. We will then set up a `rinex-publishers` group in the georust Github org, make you admins of it, and assign it crates.io publishing privileges for your crate
3. We'll add a link to the crate on georust.org

Personally, weekday mornings (GMT) are the best time for me. If and when you're ready to proceed, let's pick a day and start the process.

**Comment by gwbres** [comment]
Hello @urschrei,

thank you for your answer!

> Personally, weekday mornings (GMT) are the best time for me. If and when you're ready to proceed, 
> let's pick a day and start the process

tell me among the following list what works best for you

- Friday June 2nd 06:00 GMT 
- Monday 5th 6:00 GMT
- Wednesday 7th 6:00 GMT

When I say 6:00 GMT, i'll make sure i'm able to iniate the first step by this time. As we proceed through the morning, i can keep up with you online, either here or on your discord channel. Weekday mornings for me ends by 10:00GMT.  

There is no emergency on this topic, it can also be postoned to following weeks if that suites you best,

see you

**Comment by rmanoka** [comment]
Is this done?

**Comment by gwbres** [comment]
> Is this done?

Hello @rmanoka, no I was waiting for an answer before moving forward. But maybe should I just transfer the repo then

**Comment by rmanoka** [comment]
Thanks for confirming @gwbres ; have sent you an invite to join the georust org. on github.  Pls. accept it, and I'll create a group for the crate.   Pls. try to initial the transfer after joining the org.

**Comment by rmanoka** [comment]
Great!  Have also invited @larsnaesbye to join the organization;  the `rinex-publishers` team on `georust` now has maintain access to the `georust/rinex` repo.  We might have to tweak the crates.io settings to allow push from the above team, but it can wait till the next release.

Welcome to georust!

**Comment by rmanoka** [comment]
Closing as completed
