### ISSUE TITLE
Add more tests for `line_segmentize`

### ISSUE THREAD

**Issue by Robinlovelace** [georust/geo#1075]
As shown in https://github.com/JosiahParry/rsgeo/issues/28 there's an example where n is set to 4 but only 3 geometries are returned.

Not sure what the underlying cause is but thought it worth adding more tests to ensure it's not on the Rust side.

**Comment by urschrei** [comment]
Just checking: are these tests in addition to what's in #1078?

**Comment by JosiahParry** [comment]
I think the tests I've added in #1078 should cover the cases
