### ISSUE TITLE
Latest ahash dep and Rust 1.70.0 are incompatible

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#1149]
```
error: package `ahash v0.8.8` cannot be built because it requires rustc 1.72.0 or newer, while the currently active rustc version is 1.70.0
```

See https://github.com/georust/geo/pull/1105

**Comment by lnicola** [comment]
4 versions, or around 6 months. That's a MSRV of 1.73.

**Comment by frewsxcv** [comment]
Although we can bump our MSRV, I think it'd be easier to pin `ahash` to a specific version until we have a real need to bump the MSRV for a new feature

**Comment by frewsxcv** [comment]
This was resolved upstream https://github.com/tkaitchuck/aHash/pull/208
