### ISSUE TITLE
GeodesicDestination produces cyclcically incosistent results

### ISSUE THREAD

**Issue by joe-saronic** [georust/geo#1154]
My expectation is that repeatedly traversing a great circle with `geodesic_destination` will yield identical lat/lon/bearings up to floating point roundoff or so. I have made a small script to show some inconsistencies:

```
use geo::{GeodesicBearing, GeodesicDestination, Point};

use std::fs::OpenOptions;
use std::io::{BufWriter, Error, Write};

fn main() -> Result<(), Error> {
    let write = OpenOptions::new().write(true).create(true).open("./geodesic.csv");
    let mut writer = BufWriter::new(write.unwrap());
    let origin = Point::new(0.0, 0.0);
    writer.write("dist,lon,lat,bearing\n".as_bytes())?;
    for i in 0..1000000 {
        let dist = 100.0 * (i as f64);
        let dest = origin.geodesic_destination(45.0, dist);
        let lon = dest.x();
        let lat = dest.y();
        let bearing = (180.0 + dest.geodesic_bearing(origin)) % 360.0;
        writer.write(format!("{dist:.16},{lon:.16},{lat:.16},{bearing:.16}\n").as_bytes())?;
    }

    Ok(())
}
```

Here is a python script to plot the results against each other:

```
from matplotlib import pyplot as plt
import pandas as pd

df = pd.read_csv('./geodesic.csv')
fig, ax = plt.subplots(3, 2, constrained_layout=True)
labels = [('dist', 'lon'), ('lat', 'bearing'), ('dist', 'lat'), ('lon', 'lat'), ('dist', 'bearing'), ('lon', 'bearing')]
for a, (x, y) in zip(ax.ravel(), labels):
    a.set_xlabel(x)
    a.set_ylabel(y)
    a.plot(x, y, data=df)
```

![image](https://github.com/georust/geo/assets/156837150/17d0dc63-5b92-4306-a82d-2a8049385733)

The bearing may be a bit of a red herring in this case. However, the lat-lon relationship should in theory produce identical results with multiple passes, yet it does not appear to:

![image](https://github.com/georust/geo/assets/156837150/7a7aa1a3-47dd-414e-b1ef-0fb97562c398)

Zooming shows that the circle is rotating approximately one degree in longitude with every full rotation. This does not seem like something that is ascribable simply to round-off error.

**Comment by urschrei** [comment]
@phayes Could you have a look?

**Comment by phayes** [comment]
Hi @joe-saronic, thanks for the great bug report!  

@urschrei, can you assign this ticket to me please?

**Comment by urschrei** [comment]
Thank you! Done.

**Comment by phayes** [comment]
For anyone else following up on this ticket, travelling around a geodesic at 45 degrees should look something like this:

<img width="861" alt="image" src="https://github.com/georust/geo/assets/207037/6e50b5b0-d60e-45f7-95f4-1394f46c4d06">

Note that the only closed geodesic routes are where we are travelling at either 90 degrees (north-south), or 0 degrees (east-west) around the ellipsoid. Travelling these directions should result in a closed cyclic route. 

<img width="235" alt="image" src="https://github.com/georust/geo/assets/207037/9758d291-e8e1-4a9f-8636-d31fcfdb78b8">
