### ISSUE TITLE
Determine fate of `Geometry` enum

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#119]
What is the point of this `enum`? Doesn't seem like it serves much of a purpose. What are qualifications for a `struct`/variant to be added to it?

**Comment by urschrei** [comment]
The only practical reason I can think of is for FFI; having an enum of valid types to match against means you don't have to maintain them on the calling side.

**Comment by rory** [comment]
Personally I like this enum. For example, I've used it in my [`wkb` crate](https://crates.io/crates/wkb). If you have some WKB bytes, and you want to parse that into a geometry, you don't really know what sort of geometry you'll get out. The dataformat itself defines what type the geometry is.

**Comment by Michael-F-Bryan** [comment]
What about replacing the `Geometry` enum with a `Geometry` marker trait? 

So we could say that anything which implements `Geometry` must implement a set of commonly used algorithm traits. As a tentative list, I'd say that any "geometric object" should implement:

```rust
trait Geometry<F>: Distance<F> + BoundingBox<F> + Intersects<F> + MapCoords<F>
        + Rotate<F> + Translate<F> {}
```
- `Distance`
- `BoundingBox`
- `Intersects`
- `MapCoords`
- `Rotate`
- `Translate`

Would the ability to create trait objects for a geometric thing be useful? i.e. if we made `Geometry` a trait, would it be object safe? We could probably tweak a couple algorithms to mutate inplace v, then add a default method to return a mutated copy when `Self: Sized + Clone`... That's not exactly a small API change though, and would break a lot of existing code...

**Comment by rory** [comment]
> What about replacing the Geometry enum with a Geometry marker trait?

One question: I wrote a [Well Known Binary reader/writer](https://github.com/rory/rust-wkb), and i have a method which takes a Geometry, and then write it/encodes it. The [function](https://github.com/rory/rust-wkb/blob/16eae8ed22b2f8e4dd8d3ea62c8683866f6a5210/src/lib.rs#L100) is a big switch statement. "If it's a point do X, if a linestring do Y..." etc. Would this be possible with your suggestion?

> That's not exactly a small API change though, and would break a lot of existing code...

The crate is 0.x.y which semver says *" Anything may change at any time. The public API should not be considered stable"* so no-one should rely on it.

**Comment by frewsxcv** [comment]
> One question: I wrote a Well Known Binary reader/writer, and i have a method which takes a Geometry, and then write it/encodes it. The function is a big switch statement. "If it's a point do X, if a linestring do Y..." etc. Would this be possible with your suggestion?

You should be able to do something like this:

```rust
pub trait WkbEncondable {
    fn encode(mut result: &mut W);
}

impl<T: Float> WkbEncodable<T> for geo::Point<T> {
    fn encode(mut result: &mut W) { .. }
}

pub fn write_geom_to_wkb(geom: E, mut result: &mut W)
    where W: Write, E: WkbEncodable<T>, T: Float
{
    ...
}
```

**Comment by jdroenner** [comment]
I like the idea of the trait approach. Will rust-geo provide baseline implementations for all geometries which are currently covered by the enum? Will this be similar to `num` and `num-traits`?

**Comment by Michael-F-Bryan** [comment]
> Will rust-geo provide baseline implementations for all geometries which are currently covered by the enum?

I'm assuming that anything in the current `Geometry` enum would implement the `Geometry` trait.

I think a big question to answer if we want to use a trait instead of an enum is whether we should allow a `Geometry` to be used as a trait object. A lot of the algorithms return `Self`, meaning they wouldn't be object safe. As it is, the `Geometry` enum allows you to store a `Line` alongside a `Polygon`, but this would be no longer possible if we can't use trait objects. The only way to make the algorithms object safe would be to update them so they mutate themselves in-place, which would require a non-trivial amount of work.

One way you could make this easier (using the `Translate` algorithm as an example) is to add a required `translate_inplace()` and then add a `translate() -> Self where Self: Sized + Clone` which has a default impl that returns a mutated clone.

**Comment by frewsxcv** [comment]
Considering the use cases people shared in this thread, and the lack of a motivating reason to remove `Geometry`, I'm going to close this
