### ISSUE TITLE
`bounding_rect` comsume a lot of cpu??

### ISSUE THREAD

**Issue by yuyang-ok** [georust/geo#1200]
I do something with this library.
I am using this library to query `Geometry` 's `bounding_rect` , and using the `bounding_rect` to locate something at `RTree`.

where I notice a lot of cpu consume .
It this normal???

**Comment by yuyang-ok** [comment]
![executor-fabric-flamegraph](https://github.com/user-attachments/assets/0e87ff7f-2e91-4c9d-a73b-f1d07dde3333)
the flame graph file

**Comment by lnicola** [comment]
> `core::clone::impls::<impl core::clone::Clone for f64>::clone (600 samples, 1.19%)`

You're building with `--release`, right?

**Comment by yuyang-ok** [comment]
@lnicola  I am build release of version,otherwise all operation should slow

**Comment by lnicola** [comment]
That flamegraph makes no sense to me. `get_bounding_rect` is [pretty simple](https://github.com/georust/geo/blob/b7e7529818bab57ed1f438b4bbe6a1d672ac45b7/geo-types/src/private_utils.rs#L22), and we don't capture stack traces (`backtrace::backtrace::trace_unsynchronized`) there, it can't even panic.

**Comment by lnicola** [comment]
That's Linux, right? How did you get the flamegraph? Are you using `-Z build-std` or any profile overrides (`[profile.dev.*]` etc.)?

**Comment by yuyang-ok** [comment]
yes it's linux, I am using https://crates.io/crates/pprof to pprof

**Comment by lnicola** [comment]
Maybe [this](https://github.com/flamegraph-rs/flamegraph/blob/main/README.md)?

> Note: If you're using lld or mold on Linux, you must use the --no-rosegment flag. Otherwise perf will not be able to generate accurate stack traces ([explanation](https://crbug.com/919499#c16)).

**Comment by yuyang-ok** [comment]
I change the config still the same result.
~~~
[build]
linker = "clang"
rustflags = [ "-C", "link-arg=-fuse-ld=mold" ,  "-Clink-arg=-Wl,--no-rosegment"]
jobs = 4
incremental = false
~~~

**Comment by lnicola** [comment]
Maybe you can give `cargo-flamegraph` a try? I don't have other ideas right now.

**Comment by yuyang-ok** [comment]
@lnicola yes ,still installing toolchain.

**Comment by yuyang-ok** [comment]
I run twice I get the same error
~~~
2024-07-17T07:14:52.627767Z  INFO          task_runner ThreadId(297) gis::st_intersects2: index filter out is 3836,still need full intersects is 4
[ perf record: Woken up 25358 times to write data ]

Warning:
Processed 482187 events and lost 42 chunks!

Check IO/CPU overload!

Warning:
1 out of order events recorded.

[ perf record: Captured and wrote 6761.545 MB perf.data (425990 samples) ]
failed to sample program
~~~

**Comment by lnicola** [comment]
Hmm, that's normally just a warning, and it does produce a `perf.data` file, which you can process. But you can use something like `-F 498` to reduce the sampling frequency.

**Comment by yuyang-ok** [comment]
I think capture pprof succeeful.


![executor](https://github.com/user-attachments/assets/e726eb19-e656-47c8-becf-c7d49ec8dd09)

**Comment by yuyang-ok** [comment]
cargo-flamegraph capture less stack frame??

**Comment by lnicola** [comment]
I'm still confused about the flame graph, TBH.

Maybe it just gets called too many times? See https://docs.rs/rstar/latest/rstar/primitives/struct.CachedEnvelope.html, if `rstar` calls `envelope` a lot of times, and your polygons are large, I can see `get_bounding_rect` becoming a bottleneck.

**Comment by yuyang-ok** [comment]
Yes , I think `envelope` need call 2 million times.

**Comment by lnicola** [comment]
Can you try to insert `CachedEnvelope<Geometry<f64>>` into your `rstar` tree?

**Comment by yuyang-ok** [comment]
let me see

**Comment by yuyang-ok** [comment]
No I don't think so.

**Comment by lnicola** [comment]
Unless you can produce a test case I can run, I'll leave this for someone who actually managed to use `rstar` :sweat_smile:.

**Comment by yuyang-ok** [comment]
@lnicola thanks I will try

**Comment by yuyang-ok** [comment]
I use this code to run https://github.com/yuyang-ok/geo_parse_bounding_performance.
run quit fast.

~~~
warning: unused config key `build.linker` in `/home/yuyang/.cargo/config`
   Compiling geo_bounding_rect_performance v0.1.0 (/home/yuyang/geo_parse_bounding_performance)
    Finished `release` profile [optimized] target(s) in 1.35s
     Running `target/release/geo_bounding_rect_performance`
parse geometry and bounding_rect 10s total run:3022800
bounding_rect 1s total run:3022800
~~~

**Comment by lnicola** [comment]
Hmm, it might look different if you include the tree building.
