### ISSUE TITLE
Your Discord is not working

### ISSUE THREAD

**Issue by worikgh** [georust/geo#1211]
Hi

Following the instructions in README.md I went to your Discord server and signed up

It tells me my account is "unclaimed"

I have been through the process twice, I declined and decline to download the Discord App, and it remains read only for me

I am unsure why

My username is: worik_97831

cherio

**Comment by michaelkirk** [comment]
Are you able to post in other discord servers besides georust? I’m trying to figure out if this is a problem with our discord server or your discord account. On Aug 28, 2024, at 15:21, Worik Stanton ***@***.***> wrote:﻿
Hi
Following the instructions in README.md I went to your Discord server and signed up
It tells me my account is "unclaimed"
I have been through the process twice, I declined and decline to download the Discord App, and it remains read only for me
I am unsure why
My username is: worik_97831
cherio

**Comment by worikgh** [comment]
Silly me

It was waiting for a reply to a confirmation email

Mēh!  It did not inform me, but I should have known.  Done this for long enough!

Sorry about the noise.
