### ISSUE TITLE
Clip in BooleanOps flips some of the LineStrings in the MultiLineString

### ISSUE THREAD

**Issue by oyhj1801** [georust/geo#1245]
I'm working with directed LineStrings and when I try and clip a MultiLineString to a Polygon extent some of the LineStrings get reversed.

Before clipping:
![before_cut](https://github.com/user-attachments/assets/6a2efed0-4bf7-4565-a9de-02bf723933ff)

After clipping
![after_cut](https://github.com/user-attachments/assets/193337e8-3073-47ae-a799-a3377acd20af)

The teeth are pointing 90 degrees to the left of the direction of the LineString.
In the upper image some LineStrings are on top of each other where two tiles overlap, after clipping all map-tiles to the intended extent, no LinesStrings overlap but some have been reversed (indicated by the teeth pointing in the opposite direction) as can be seen in the bottom image.

**Comment by michaelkirk** [comment]
Are you seeing this on geo-0.29.0, just released yesterday? There was a major change to the clip operation.

Can you please provide a minimal example of the data set that produces this behavior?

**Comment by oyhj1801** [comment]
Yes this is on geo-0.29.0

I'll try and find an example

**Comment by oyhj1801** [comment]
The reversing seems to consistently happen when a LineString doubles back on it self outside of the clip extent.
Here is one example of the bug for a MultiLineString containing only a single LineString for a LineString generated by my program followed by a minimal example.
![clip_error](https://github.com/user-attachments/assets/9e230272-26cd-4d03-910a-629766cede64)
![minimal_error](https://github.com/user-attachments/assets/208bb0c8-8b85-448e-b8ee-6248f94915ec)
The red line is the input MulitLineString, containing only a single LineString, the green and blue are the output after clipping. The star symbolizes the end of a LineString.

**Comment by dabreegster** [comment]
Do you have sample input data as WKT, GeoJSON, etc? Ideally a minimally runnable script that shows this behavior

**Comment by oyhj1801** [comment]
use geo::{coord, BooleanOps, LineString, MultiLineString, Polygon};

fn main() {
    // for any positive values in max coord > 3
    let max = coord! {x: 6., y: 6.};

    let extent = Polygon::new(
        LineString::new(vec![
            coord! {x: 0., y: max.y},
            coord! {x: 0., y: 0.},
            coord! {x: max.x, y: 0.},
            coord! {x: max.x, y: max.y},
            coord! {x: 0., y: max.y},
        ]),
        vec![],
    );

    let lines = MultiLineString::new(vec![LineString::new(vec![
        coord! {x: -1., y: max.y-1.},
        coord! {x: max.x-1., y: -1.},
        coord! {x: -1., y: 2.},
    ])]);

    let expected = MultiLineString::new(vec![
        LineString::new(vec![
            coord! {x: 0., y: max.y-1. - max.y/max.x * 1.},
            coord! {x: -1. + max.x/max.y * (max.y - 1.0), y: 0.},
        ]),
        LineString::new(vec![
            coord! {x: max.x-1. - max.x/3. * 1., y: 0.},
            coord! {x: 0., y: -1. - 3./max.x * -(max.x-1.)},
        ]),
    ]);

    let clipped_lines = extent.clip(&lines, false);

    println!("clip extent: {:?}", extent);
    println!("input: {:?}", lines);
    println!("output: {:?}", clipped_lines);
    println!(
        "expected: {:?} (ordered as encountered along the input)",
        expected
    );
}


Here you can see that the output differs from the expected in both the order of the segments (not important for me and guessing clip is not supposed to preserve 'internal' order anyways) and flips one of the output segments

**Comment by michaelkirk** [comment]
Thank you for the good reproduction @oyhj1801, and thank you for taking prompt interest @NailxSharipov!

**Comment by frewsxcv** [comment]
iOverlay 1.9.0 just landed in `geo` (https://github.com/georust/geo/pull/1275). So this should be fixed on `main`, and as soon as we push a new release which should hopefully be soon

**Comment by frewsxcv** [comment]
A new version of geo was published which includes the fix
