### ISSUE TITLE
Do polygons need to be closed?

### ISSUE THREAD

**Issue by Michael-F-Bryan** [georust/geo#166]
I don't think it specifies in the documentation whether a polygon should be closed or not, although I'm assuming that's an implicit assumption. 

Would it be worth adding this in `Polygon`'s docs (and possibly adding a `debug_assert!()` in the constructor) if this constraint must be upheld?

**Comment by rory** [comment]
I also wondered about this, I have been closing my polygons (ie last point = first point). At a minimum the docs should clarify this.

**Comment by urschrei** [comment]
According to the OpenGeo spec, [the outer boundary of a Polygon must be closed and simple](https://connect.boundlessgeo.com/docs/suite/4.8/dataadmin/pgBasics/geometries.html#polygons). A debug assert is a good idea, but I think we should be implicitly closing Polygons when the `new` method is called, and making that clear in the docs (it's what Shapely does, not totally sure about JTS / GEOS, but TestBuilder does it too) – there will be lots of cases where they're constructed at runtime. This is part of the larger "should it be possible to construct invalid geometries" discussion, but in this case, it's a fundamental problem if the shell is left open.

**Comment by rory** [comment]
Idea: Automatically close the linestrings if they are not closed. Just look if the first & last are the same, and if not `.clone()` and `.push(...)`. You know what the user is trying to do.

*But* (and this goes back to the validity argument) is it worth having some sort of `.new_unchecked()` method which just takes what you give it (potentially resulting in invalid geometries).

**Comment by Michael-F-Bryan** [comment]
It's probably not. A `.clone()` in this case is just copying a pair of floats and appending them to your line. It might be expensive if the line's inner `Vec` is at full capacity and the push forces it to resize, but I'm going to assume that's a fairly rare edge case.

**Comment by urschrei** [comment]
Another (probably rare in practice) downside is if you keep the original Vec around and construct the Polygon by cloning it. If you depend on their equality (or even the length being the same), that's going to cause problems.

**Comment by rory** [comment]
My suggestion for `.new_unchecked()` is not for performance reasons, but because I think it's good to have a way for the user (of the library) to say "No, I *really* know what I'm doing, Yes I'm willing to deal with the consequences". Sort of a unix philosophy for software libraries. :)

**Comment by urschrei** [comment]
I agree with that in principle, but in the interest of striking a balance between "no surprises", and API bloat, I think it'd be good to come up with at least one reason why a user might want to do that.

**Comment by Michael-F-Bryan** [comment]
Well all the components of `Polygon` are public, so if a user wants to create a new `Polygon` without checking to see if it's closed they can always construct one directly.

We can always adjust the docs for `Polygon::new()` to say

```diff
- Creates a new polygon.
+ Creates a new polygon, closing it if the exterior or any of the interior 
+ rings aren't already closed.
```

The wording could do with some work, but you get the gist.

**Comment by frewsxcv** [comment]
Drawing a parallel in the standard library, the [`CString::new`](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.new) function checks to make sure that the supplied bytes has a trailing `\0` byte, and if it doesn't, appends a `\0` byte. There's also a [`CString::from_vec_unchecked`](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.from_vec_unchecked) `unsafe` function if you're _certain_ that your bytes have a trailing `\0`.

**Comment by urschrei** [comment]
It occurs to me that there's an additional use case here: constructing geometries using immutable slices (I know this isn't possible today, but it's certainly desirable, whether because we want to avoid allocations, or in an FFI scenario). We have to check that the shell and rings are valid when the Polygon is constructed, but we can't modify them, so we have to return a `Result`.

**Comment by frewsxcv** [comment]
Opened a pull request that addresses this: https://github.com/georust/geo/pull/337
