### ISSUE TITLE
Replace '-> Box<Iterator>' with '-> impl Iterator' once return impls stabilize

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#198]
https://github.com/georust/rust-geo/blob/f082fe8656bf9a0a1639d5b4d28f2e0f6df369ee/src/types.rs#L642

**Comment by lnicola** [comment]
`lines` can be easily replaced. `points_cw` and `points_ccw` however, depend on https://github.com/rust-lang/rust/issues/34511.

**Comment by frewsxcv** [comment]
gonna close this. we don't have any instances of `Box<Iterator>` anymore
