### ISSUE TITLE
geo structs

### ISSUE THREAD

**Issue by calvinmetcalf** [georust/geo#2]
basic geo types need to be defined, some basics
- point, line and poygons
- how to deal with multi versions, separate type or points/line/polygon always store the type in a vector
- minimum number of distinct points in a line (geojson is 2, shapefiles is 1).
- minimum number of distinct points in a polygon (geojson is 3 plus first and last must be the same so 4 total, esri does not have first and last be the same).
- winding order, does it matter (geojson no, esrijson clockwise is a polygon and counterclockwise is a hole).
- if winding order doesn't matter how do you deal with polygons that cross into multiple hemispheres
- how do you deal with holes in polygons (geojson has a polygon object be an outer ring followed by zero or more inner rings, esrijson uses winding order).
- how do you deal with self intersecting polygons.
- how do you deal with polygons which intersect their own holes.
- do we deal with typologies
- how many dimensions
- geometry collections (esri does not touch this)
- projections and that whole can of shit ...

**Comment by sunng87** [comment]
Perhaps we can follow some open standard like [OGC Simple Feature Access](http://www.opengeospatial.org/standards/sfa)

To answer some questions above (Just my opinion)

1. Base types: Point, LineString, Polygon; there are also some other types as defined in SFA 6.1 Geometry Object Model
2. Hole in polygon is represented as InteriorRing (A LineString). A polygon has only one exterorRing and 0 or multiple interiorRing. So wind order doesn't matter.
3. Self intersecting polygons are not supported (? you may check the definition in that document to confirm)
4. We don't need to deal with topology in this lib
5. (x,y) is required and `z`, `m` is optional
6. GeometryCollection is in this spec
7. Projections are out of this library's scope, only numeric coordinates are involved

**Comment by calvinmetcalf** [comment]
not a bad idea, the way point xy is distinct from point xyz fits well with rust fyi ogc has the same types as geojson (Point,LineString,Polygon,MultiPoint,MultiLineString,MultiPolygon,GeometryCollection) plus a few more (MultiCurve, MultiSurface,Curve, Surface, PolyhedralSurface, TIN).

The GeoJSON and some databases like postgres have a somewhat laxer view on self intersections and what not, then tends to be a bit more practical in the real world.

The OGC spec is awful, the page number are romen numerals for gods sack.

Hemisphere spanning polygons are still a problem

**Comment by sunng87** [comment]
SFA GOM is based on a classic object-oriented model, but in rust we prefer composition over inheritance, so we don't need to implement types like Curve, Surface...

I think the shared types of SFA and GeoJSON are in highest priority. 

Another reference is [JTS geom types](http://tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/geom/package-frame.html). JTS is widely used in Java GIS libraries as foundation. You can find its type system is very practical.

**Comment by frewsxcv** [comment]
Maybe we should open separate GitHub issues to discuss each of these points individually to facilitate better, more organized discussion.

In terms of XYZM, does the M coordinate value ever get used for geospatial calculations like distance and area? [After reading this](https://gis.stackexchange.com/questions/39131/what-is-an-xyzm-measurement-model) I would think that it wouldn't.

**Comment by calvinmetcalf** [comment]
yeah m is rarely used, wkb specifically is pretty down to earth and is something we could translate into rust pretty easily

**Comment by frewsxcv** [comment]
Unless I'm looking at this incorrectly, [it looks like JTS's distance operation only works on XY](https://github.com/simplegeo/jts/blob/master/src/com/vividsolutions/jts/operation/distance/DistanceOp.java) even though they offer XYZ (and M).

**Comment by sunng87** [comment]
True, seems the whole library don't use z for distance: https://github.com/simplegeo/jts/blob/master/src/com/vividsolutions/jts/algorithm/CGAlgorithms.java

**Comment by frewsxcv** [comment]
Well, it's been just about ten years since this was opened and last discussed 👋🏻 

I'm going to close this, but if there are any remaining discussions to have here, we can open a new issue for it.
