### ISSUE TITLE
Proposal: Introduce `geo::GeoBuf` struct, alter `geo::Geo` struct

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#21]
# Idea

Currently, there exists just `geo::Geo`, which is a structure containing **owned** data. I propose we rename this to `geo::GeoBuf` and introduce a new structure containing **borrowed** data called `geo::Geo`. Table of similar analogies:

| Owned | Borrowed |
| --- | --- |
| [`Vec`](https://doc.rust-lang.org/std/vec/struct.Vec.html) | [`slice`](https://doc.rust-lang.org/std/primitive.slice.html) |
| [`String`](https://doc.rust-lang.org/std/string/struct.String.html) | [`str`](https://doc.rust-lang.org/std/primitive.str.html) |
| [`PathBuf`](https://doc.rust-lang.org/std/path/struct.PathBuf.html) | [`Path`](https://doc.rust-lang.org/std/path/struct.Path.html) |
| `GeoBuf` | `Geo` |
# Reasoning

Currently, if there exists a method `centerpoint` on `Geo`, and I want to apply this operation on a `Wkt` struct (from rust-wkt), I have to convert my `Wkt` struct to a `Geo`, and since `Geo` is **owned**, this results in memory allocations occurring.

With my proposal above, we would just need to interpret the `Wkt` struct as the new **borrowed** `Geo`, which results in a `Geo` struct that references the existing data in the `Wkt` struct, resulting in no new memory allocations.
# Implementation

`struct Geo` will be renamed to `struct GeoBuf`

`struct Geo` will be a new struct with borrowed fields. Not too sure how this will look right now, but it's do-able.

`Deref<Target=Geo>` will be implemented on `GeoBuf`

**Comment by frewsxcv** [comment]
On second thought, I forgot that we have separate structs for each geometry type (e.g. `MultiPoint`, `Point`, etc.). Not sure how that would work...

**Comment by frewsxcv** [comment]
Another option here:

```diff
diff --git a/src/types.rs b/src/types.rs
index e304dcd..45c12cc 100644
--- a/src/types.rs
+++ b/src/types.rs
@@ -1,6 +1,7 @@
 use std::ops::Add;
 use std::ops::Neg;
 use std::ops::Sub;
+use std::borrow::Cow;
 
 #[derive(PartialEq, Clone, Copy, Debug)]
 pub struct Coordinate {
@@ -225,17 +226,17 @@ pub struct Polygon(pub LineString, pub Vec<LineString>);
 pub struct MultiPolygon(pub Vec<Polygon>);
 
 #[derive(PartialEq, Clone, Debug)]
-pub struct GeometryCollection(pub Vec<Geometry>);
+pub struct GeometryCollection<'a>(pub &'a [Geometry<'a>]);
 
 #[derive(PartialEq, Clone, Debug)]
-pub enum Geometry {
-    Point(Point),
-    LineString(LineString),
-    Polygon(Polygon),
-    MultiPoint(MultiPoint),
-    MultiLineString(MultiLineString),
-    MultiPolygon(MultiPolygon),
-    GeometryCollection(GeometryCollection)
+pub enum Geometry<'a> {
+    Point(Cow<'a, Point>),
+    LineString(Cow<'a, LineString>),
+    Polygon(Cow<'a, Polygon>),
+    MultiPoint(Cow<'a, MultiPoint>),
+    MultiLineString(Cow<'a, MultiLineString>),
+    MultiPolygon(Cow<'a, MultiPolygon>),
+    GeometryCollection(GeometryCollection<'a>)
 }
 
 #[cfg(test)]

```

**Comment by frewsxcv** [comment]
This might no longer need to happen if https://github.com/georust/rust-geo/issues/67 gets resolved.

**Comment by kylebarron** [comment]
Just curious, is there still interest in this? Is there a way today to use geo geometries from borrowed data? Or is the thought that in the long term geo traits will hopefully solve this use case?
