### ISSUE TITLE
Euclidean distance algorithm incorrect?

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#291]
Relevant issue about return units for distance algorithms: https://github.com/georust/rust-geo/issues/194

I'm having trouble getting an intuitive understanding of the return value is for our `EuclideanDistance` and `EuclideanLength` algorithm traits.

To demonstrate this, here's a little script I put together:

```rust
use geo::prelude::*;

const MEAN_EARTH_RADIUS: f64 = 6_371_000.0;

fn main() -> Result<(), Box<Error>> {
    let reykjavik = geo::Point(geo::Coordinate { y: 64.1265, x: -21.8174 });
    let nyc = geo::Point(geo::Coordinate { y: 40.7128, x: -74.0060 });

    println!("old euclidean distance: {}", reykjavik.euclidean_distance(&nyc) * MEAN_EARTH_RADIUS);
    println!("new euclidean distance: {}", new_euclidean_distance(&reykjavik, &nyc));
    println!("haversine distance: {}", reykjavik.haversine_distance(&nyc));
    println!("vincenty distance: {}", reykjavik.vincenty_distance(&nyc)?);

    Ok(())
}

fn new_euclidean_distance(p1: &geo::Point<f64>, p2: &geo::Point<f64>) -> f64 {
    let x1 = p1.x().to_radians();
    let y1 = p1.y().to_radians();
    let x2 = p2.x().to_radians();
    let y2 = p2.y().to_radians();

    let x = (x2 - x1) * ((y1 + y2) / 2.).cos();
    let y = y2 - y1;
    x.hypot(y) * MEAN_EARTH_RADIUS
}
```

```
old euclidean distance: 6360360.804629714
new euclidean distance: 4393608.165461339
haversine distance: 4208198.758424172
vincenty distance: 4217509.479276674
```

The `new_euclidean_distance` function above is the [algorithm mentioned on this page](http://www.movable-type.co.uk/scripts/latlong.html?from=64.1265,-21.8174&to=40.7128,-74.0060#equirectangular).

**Comment by urschrei** [comment]
Yep, that's also my understanding.

**Comment by geodesicdome** [comment]
Haversine takes into to account the Radius where as Vincenty's takes into account ellipsoid determined via geodetic survey(ie WGS)

**Comment by frewsxcv** [comment]
One other question I've been wondering: is there some pythagorean-esque algorithm that works for pairs of coordinates near the international date line, but on opposite sides? For example, calculating the [distance from Wake Island to Hawaii](https://www.google.com/search?client=firefox-b-1-d&q=distance+from+wake+island+to+hawaii)

**Comment by frewsxcv** [comment]
Also, in case anyone has any good books or online resources about geospatial distances or, more generally, the math behind geospatial algorithms, I'd love to get a better understanding here

**Comment by TeXitoi** [comment]
I suppose you know https://en.wikipedia.org/wiki/Geographical_distance

For Wake Island to Hawaii, https://en.wikipedia.org/wiki/Geographical_distance#Spherical_Earth_projected_to_a_plane is working as long as you check that your delta is within [0, 180°[

**Comment by kuttamuwa** [comment]
The context : GIS ( Geographic Information System)

I can refer some library in python can do those things : shapely, arcpy (
ESRI's python library, licensed).
The real sources are : GDAL, OSGEO, QGIS and GrassGIS. QGIS and GrassGIS
are programs developed in C++ and have bindings for Python.

The books.. Yes there are some books in google while searched as GIS
algorithms :
https://books.google.com.tr/books?id=P6NiCgAAQBAJ&pg=PT344&lpg=PT344&dq=geospatial+algorithms+gdal&source=bl&ots=olcA7e4Pl4&sig=ACfU3U2mb8WIuGT5jrMNfFOdF0gfHlGmEw&hl=tr&sa=X&ved=2ahUKEwjOzNazqongAhWQr6QKHalzAV4Q6AEwAnoECAkQAQ#v=onepage&q=geospatial%20algorithms%20gdal&f=false

And CGAL is very advanced library for C
https://www.cgal.org/
There must be some pseudo code i think.
https://books.google.com.tr/books?id=4p1zYJ9BDFAC&pg=PA974&lpg=PA974&dq=geospatial+algorithms+gdal&source=bl&ots=mEl7jekRp-&sig=ACfU3U3MTmkI7shvti0WO-dZT-CMxMnuNQ&hl=tr&sa=X&ved=2ahUKEwjOzNazqongAhWQr6QKHalzAV4Q6AEwA3oECAcQAQ#v=onepage&q=geospatial%20algorithms%20gdal&f=false

However, you can find real theorical informations in geomatics engineering
books. Geodesy is your main keywords.
I want to contribute to your lib but first i need to learn more Rust :(


Corey Farwell <notifications@github.com>, 25 Oca 2019 Cum, 16:59 tarihinde
şunu yazdı:

**Comment by michaelkirk** [comment]
I believe this has been answered. Feel free to reopen if there's more to the question than I thought.
