### ISSUE TITLE
Add `to_radians` and `to_degrees` helpers methods on Point

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#293]
https://doc.rust-lang.org/std/primitive.f32.html#method.to_degrees

https://doc.rust-lang.org/std/primitive.f32.html#method.to_radians

**Comment by Jay9596** [comment]
Hi! 👋
I want to work on this, if it's not assigned to anybody.

**Comment by frewsxcv** [comment]
Go for it!

**Comment by Jay9596** [comment]
From what I understand, I have to add methods `to_radian` and `to_degree` for Point struct.
They will return a _new_ Point with `self.x`, and `self.y` in respective degree or radian, and use the primitive methods availabe for f32 to convert.

Anything missing / incorrect ?

**Comment by frewsxcv** [comment]
Yep, that all sounds right to me 👍

**Comment by Jay9596** [comment]
I got a function going, but I'm stuck on changing the f32 to T type.
```rust
pub fn to_degree(&self) -> Point<T> {
        let (x, y) = self.x_y();
        let x= x.to_f32().unwrap().to_degrees();
        let y = y.to_f32().unwrap().to_degrees();
        Point::new(x, y)
} 
```
I read about `num_traits::FromPrimitive`, but I don't understand how to call it.
How do I convert the f32 back to T type.

**Comment by frewsxcv** [comment]
Ah so the `num_traits` crate provides a _generic_ `to_radians` method on `Float` that we can use:

- https://docs.rs/num/0.2.0/num/trait.Float.html#method.to_radians

But our `CoordinateType`doesn't extend `Float`:

https://github.com/georust/geo/blob/42f1c3bdf7c72a0186f98f82e8fdf3b233ce4774/geo-types/src/lib.rs#L16

Our `CoordinateType` doesn't extend `Float` because we allow the user to use non-floating-point integer types as `T` (https://github.com/georust/geo/issues/137).

So what we'll need to do is create a new `impl` block in `Point` that specifies `T` should be both `CoordinateType` _and_ `Float`, but just for these new methods:

```rust
impl<T> Point<T>
where
    T: CoordinateType + Float,
{
    pub fn to_degrees(&self) -> Point<T> 
        let (x, y) = self.x_y();
        let x = x.to_degrees();
        let y = y.to_degrees();
        Point::new(x, y)
    }

    ...
}
```

Let me know if that doesn't make sense and I can explain further! 👋

**Comment by Jay9596** [comment]
This was very helpful. Thanks a lot.
I've made a PR #306 , please review it. 
Please check if the documentation is up to mark, I'm not too confident about that. 😅

**Comment by frewsxcv** [comment]
done in https://github.com/georust/geo/pull/306
