### ISSUE TITLE
Update `spade` to 1.6

### ISSUE THREAD

**Issue by nevi-me** [georust/geo#308]
`spade` has been updated to 1.6, with the main impact being that the transitive dependency on `rustc_serialize` is removed.  This will allow compiling `geo` to wasm per my attempts in #245.

I'll update and submit a PR when I get a chance.

**Comment by frewsxcv** [comment]
We may not need this after https://github.com/georust/geo/pull/314

**Comment by frewsxcv** [comment]
#314 has merged and been published
