### ISSUE TITLE
Unable to enable serde

### ISSUE THREAD

**Issue by AdamRzepka** [georust/geo#312]
It is possible, that I'm doing something wrong, but I believe, that it is now impossible to use `serde` with `geo`. I need to serialize `Rect` type from `geo-types`. It must have enabled `"use-serde"` to derive `Serialize` and `Deserialize`. However, such feature is not listed in `geo-types/Cargo.toml` (note: it is listed in `geo/Cargo.toml` but not propagated from there into `geo-types`).

**Comment by frewsxcv** [comment]
it _should_ be propagated because `geo-types/serde` is specified in the array here:

https://github.com/georust/geo/blob/master/geo/Cargo.toml#L29

the issue here is this line:

https://github.com/georust/geo/blob/master/geo-types/src/rect.rs#L4

this should be `serde`, not `with-serde`

**Comment by frewsxcv** [comment]
ideally `geo`'s feature would also just be called `serde`, but that's currently behind a feature flag in cargo: https://github.com/rust-lang-nursery/api-guidelines/issues/180

**Comment by frewsxcv** [comment]
regarding the `with-serde` typo on `Rect`, i can fix it later, or if you get to it first, feel free to open a pull request
