### ISSUE TITLE
Confusion when working with geo, geo_types and geojson crates

### ISSUE THREAD

**Issue by stuartlynn** [georust/geo#333]
Apologies if this is an obvious question but I am newish to rust and I am struggling to get my head around how to use these three packages together. 

I am trying to write a really simple program that will read in a geojson file that contains a geometry collection that of either polygons or multipolygons and then simple outputs their area. I want to do more than that eventually but this is just the simple test case I am trying to understand these libraries.

```rust
extern crate geo;
extern crate geojson;
extern crate geo_types;

use geojson::conversion::TryInto;
use geo::prelude::*;

use geo_types::{LineString, MultiPoint, MultiPolygon, Point, Polygon, Geometry};
use geojson::{Error as GjErr, Feature, FeatureCollection, GeoJson,  Value};

use std::env;
use std::fs;


fn calc_areas(fc : geojson::FeatureCollection) {

    for feature in fc.features{
        let geom = feature.geometry.unwrap();
        let vals = feature.properties;

        let area = match geom.value{
            geojson::Value::Polygon(poly) =>{
                let p: Polygon<f64> = geom.value.try_into().unwrap();
                p.area()
            },
            geojson::Value::MultiPolygon(poly) => {
                let p: MultiPolygon<f64> = geom.value.try_into().unwrap();
                p.area()
            },
            _ => panic!("not a polygon or multipolygon")
        };

        println!("area is {}",area);
    }
}

fn main() {
    let args: Vec<String> = env::args().collect();
    let filename = &args[1];

    println!("loading file {}",filename);
    let contents = fs::read_to_string(filename)
                .expect("Something went wrong reading the file");
    let geojson = contents.parse::<GeoJson>().unwrap();

    let points = match geojson {
         GeoJson::FeatureCollection( ctn) => {
            println!("Found {} features", ctn.features.len());
            calc_areas(ctn);
         },
         _ => {
             panic!("Looking for a feature collection buy didnt find one");
         }
    };
}
```

The problem I am running in to is that if I try to compile the code above, I get the error: `no method named `area` found for type `geo_types::Polygon<f64>` which is fair enough but if I change it to something like 

```rust 
 let p: geo::Polygon<f64> = geom.value.try_into().unwrap();
```
etc, then the try_into conversion fails. It looks like the geo crate just re-exports the geo-types structs but I can't see how both do the conversion and run the area trait. 

Thanks for any advice and I would be happy to write some of these kinds of uses cases up as examples as well for other people who are new to rust and the geo libraries to learn off of.

**Comment by stuartlynn** [comment]
That sorted it thanks!

**Comment by frewsxcv** [comment]
sorry for the confusion! i just bumped the geojson crate (to 0.14.0) to support geo-types 0.3 https://github.com/georust/geojson/pull/109
