### ISSUE TITLE
Implement BoundingRect for Rect

### ISSUE THREAD

**Issue by software-opal** [georust/geo#354]
I know this sounds silly, but I have 2 use cases in which having the `BoundingRect` trait would help.

## Use case 1 -- Normalising min/max
I'm getting into this situation by applying a `map_coords` function; but could also be useful for the general case. 
```rust
let rect = Rect { min: (10, 20).into(), max: (20, 10).into() };
let rect = rect.bounding_rect();
assert_eq(rect.min.x_y(), (10, 10));
```

## Use case 2 -- A function accepting some bounds

```rust
fn do_thing_with_bounds(geometry: BoundingRect<f64, Output=Rect<f64>>) {
  // ...
}

do_thing_with_bounds(line);
// See note below
do_thing_with_bounds(polygon.bounding_rect().unwrap());
```

An extension of this would be adding a `TryBoundingRect` trait, which would always return an `Option<Rect>`. This would allow code to accept any sort of geometry and perform actions on the bounding box.

**Comment by frewsxcv** [comment]
Thanks for bringing this up @software-opal! Regarding your first use case, how do you end up with a `Rect` where `min` does not have minimum x/y values? Maybe we should have a `new` constructor on `Rect` that enforces that the `max` x/y values are larger than the `min` x/y values
