### ISSUE TITLE
Bump rstar in geo-types to 0.4.0

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#361]
Gonna hold off on this until we're ready to do a geo-types bump.

**Comment by Stoeoef** [comment]
I've recently published 0.4.0. Only new features were added, hopefully no bug this time...
You should not see any breaking changes in regards to rstar's API surface.

**Comment by urschrei** [comment]
Just trying to fix this, and getting a confusing error related to `RTreeObject`:

    the trait `rstar::Point` is not implemented for geo_types::Line<T>
    note: required because of the requirements on the impl of rstar::RTreeObject for geo_types::Line<T>
    note: required by rstar::RTree

I'm not sure why this is arising, since our `Point<T>` has an `rstar::Point` impl…

**Comment by Stoeoef** [comment]
Just bumping the version information works for me ([comparison](https://github.com/georust/geo/compare/master...Stoeoef:master)), all tests pass and the benchmarks run on nightly. What did you do differently?

**Comment by urschrei** [comment]
@Stoeoef I think I bumped the `geo_types` version without bumping the `geo` version 🤦‍♂️. Works fine here too.
