### ISSUE TITLE
Remove Guillemets from doc examples

### ISSUE THREAD

**Issue by urschrei** [georust/geo#365]
Somehow, Guillemets have snuck into a few of the [doc examples for the new macros](https://github.com/georust/geo/blame/master/geo-types/src/macros.rs#L4). I'm not sure how that happened. Can we just delete them @frewsxcv, or is it a substitution?

**Comment by frewsxcv** [comment]
I intentionally added those in [this pull request](https://github.com/georust/geo/pull/352). I wanted someway to express that the macros take a coordinate pair _or_ `Coordinate` struct. Here were a few ways I was trying to represent that in the docs:

```rust
line_string![(Coordinate OR (x:, y:)), …]
```

```rust
line_string![<Coordinate || (x:, y)>, …]
```

```rust
line_string![«Coordinate|(x,y)», …]
```

And I ended up going with the last one. But I'm open to changing it! I definitely don't feel strongly about this
