### ISSUE TITLE
don't mix x/y and lat/lon

### ISSUE THREAD

**Issue by jdroenner** [georust/geo#37]
The `Point` struct has both `x/y` and `lat/lon` getter methods. This can be confusing when both are used in the same method.

Additionally i think using `lat/lon` is very dangerous in general. My experience is that many people think x = lat and y = lon ...

**Comment by TeXitoi** [comment]
What do you propose? removing getter/setter lat/lon?

I think that these getter/setter are very useful. Else, when we work with geographical coordinates, using x and y is very error prone.

**Comment by frewsxcv** [comment]
Does anyone know what similar libraries use? (e.g. go.geo, OGR, etc.)

**Comment by jdroenner** [comment]
You are right, for geographic coordinates lat/lon are very useful. But there are also non-geographic (e.g. projected) spatial coordinates where lat/lon makes no sense.
I think that each algorithm should only use one of them and generic algorithms should only use x/y.

**Comment by TeXitoi** [comment]
@jdroenner I agree with that

**Comment by jdroenner** [comment]
[JTS uses x,y (z)](http://tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/geom/Point.html)
The [OGC Simple Feature Access](http://www.opengeospatial.org/standards/sfa) also defines points as x,y (z).
The OGC spec is implemented in most database systems (Oracle, SQL Server, PostGIS, Mysql).

**Comment by TeXitoi** [comment]
boost geometry use 
```c++
double x = bg::get<0>(point);
double y = bg::get<1>(point);
```

As you should implement that for your own struct, you can use whatever you want.

**Comment by jdroenner** [comment]
We could change `Coordinate` to be a tuple to get `.0` and `.1` ;)

**Comment by TeXitoi** [comment]
@jdroenner please no ;)

**Comment by frewsxcv** [comment]
I'm fine with `x`, `y`, `lng`, `lon`, `lat`. I'm against `.0` and `.1` because it's not obvious if the user is dealing with `longitude, latitude` or `latitude, longitude`.

**Comment by frewsxcv** [comment]
Relevant: http://www.macwright.org/lonlat/

**Comment by jdroenner** [comment]
Well i guess the important part is to not mix x/y and lat/lon. Can we enforce this somehow?

@frewsxcv web based GIS is an area where very strange things happen ;) The axis ordering in WMS was switched between two versions and this is still confusing.

**Comment by urschrei** [comment]
@Indy2222 This feature exists in the form of the optional `Project` and `Convert` traits, see https://github.com/georust/rust-geo/pull/192 (note that the `MapCoordsFallible` trait has become `TryMapCoords`. As of now, the vast majority of `Geo`'s functionality is predicated on planar coordinates (or coordinates in planar projections), which is signalled by the use `euclidean` for clarity where necessary, and `haversine` for e.g. spherical coordinates.

**Comment by frewsxcv** [comment]
How do people feel about dropping the `lng` and `lat` methods? Would that be a satisfying resolution here?

**Comment by urschrei** [comment]
I think so. The only potential users of lat / lng I can think of might be the CanalTP people, just because it's an older codebase. In any case, we could deprecate with a "we'll be dropping this in 1.0" message?

**Comment by frewsxcv** [comment]
Great, let's deprecate them then with the plan to remove them in a future breaking change release.

**Comment by frewsxcv** [comment]
https://github.com/georust/geo/issues/710
