### ISSUE TITLE
Euclidean Line-Line distance is not symmetrical

### ISSUE THREAD

**Issue by Wassasin** [georust/geo#370]
The Euclidean Line-Line distance does not compute a correct value. I added this unit test:
```
let line0 = Line::from([(0., 0.), (5., 0.)]);
let line1 = Line::from([(2., 1.), (7., 2.)]);
assert_eq!(line0.euclidean_distance(&line1), 1.);
assert_eq!(line1.euclidean_distance(&line0), 1.);
```
This currently outputs: `1.5689290811054721` for the first assertion, and `1.0` for the second.
I would expect this operation to be symmetrical and output `1.0`.

**Comment by frewsxcv** [comment]
Is this a bug in this implementation?

https://github.com/georust/geo/blob/4bc98b953fb01b95d7a0165e7bc83ca21d0ddffe/geo/src/algorithm/euclidean_distance.rs#L221-L229

In particular:

https://github.com/georust/geo/blob/4bc98b953fb01b95d7a0165e7bc83ca21d0ddffe/geo-types/src/private_utils.rs#L75-L94
