### ISSUE TITLE
Add new Coordinate struct with support for Hash when CoordinateType implements Hash

### ISSUE THREAD

**Issue by nick-parker** [georust/geo#383]
I'm working on some algorithms that could really use both hashmaps of 2D coordinates and the features of various geo_types based crates eg offset_polygon and rust-geo-booleanop.

I'm using NotNan numbers from ordered-float inside of nalgebra Point2s right now and the hash based stuff works great. Would it be feasible to somehow make this library generic over two different Coordinate structs? One that's only got PartialEq like the current implementation, and one with full Eq and Hash for use cases where that's possible?

It seems like this would also be valuable for people working with int coordinates or fixed precision ones.

**Comment by nick-parker** [comment]
Awesome, thanks @frewsxcv!! This is also a neat little lesson in Rust's type system for me. Of course you just needed some extra impl's in the right places...

**Comment by guidorice** [comment]
Just a heads-up that `cargo clippy` reports a number of errors related to the impl Hash for geo-types:

```
error: you are implementing `Hash` explicitly but have derived `PartialEq`
  --> geo-types/src/rect.rs:88:1
   |
88 | / impl<T: CoordinateType + Hash> Hash for Rect<T> {
89 | |     fn hash<H: Hasher>(&self, state: &mut H) {
90 | |         self.min.hash(state);
91 | |         self.max.hash(state);
92 | |     }
93 | | }
   | |_^
   |
note: `PartialEq` implemented here
  --> geo-types/src/rect.rs:5:10
   |
5  | #[derive(PartialEq, Clone, Copy, Debug)]
   |          ^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_hash_xor_eq
```
