### ISSUE TITLE
Possible invalid documentation

### ISSUE THREAD

**Issue by N3xed** [georust/geo#384]
In the documentation for the function ´geo::Rect::new´ it sais: 
> Constructor to creates a new rectangle from coordinates, where `min` denotes to the
> coordinates of the ***bottom-right*** corner, and `max` denotes to the coordinates of the
> ***top-left*** corner

Shouldn't it be that `max` denotes the top-right and `min` the bottom-left corner?
Otherwise the validity check wouldn't make much sense:
> assert!(min.x <= max.x && min.y <= max.y, "[..]");

So `min` must be down-left from `max` (or equal).

**Comment by frewsxcv** [comment]
Good catch! Fixed in https://github.com/georust/geo/pull/385
