### ISSUE TITLE
Replacing Failure with std::Error and a helper crate.

### ISSUE THREAD

**Issue by urschrei** [georust/geo#387]
Using `Failure` was my (with the benefit of hindsight, premature) call, and it obviously hasn't worked out as intended. With the proliferation of helper crates that don't appear in the public API (snafu, thiserror), I think it would be best to go with that model, and present a `GeoError` enum that implements `std::Error`. This will also require a change to Geojson and one or two other crates, but not to worry…

**Comment by frewsxcv** [comment]
https://github.com/georust/geo/pull/388
