### ISSUE TITLE
geo/.travis.yml installs older version of Proj (proj-5.2.0)

### ISSUE THREAD

**Issue by guidorice** [georust/geo#396]
`geo/.travis.yml` installs older version of Proj (proj-5.2.0) but `proj` and `proj-sys` installs proj-6.2 their respective `geo/.travis.yml` files.

I ran across this in the process of creating a Dockerfile I could use for georust development.

Is it an error? Which version should I install in my dev environment?

**Comment by guidorice** [comment]
Relates to #393

**Comment by urschrei** [comment]
It should be installing PROJ 6.2, and using `proj` crate version 0.10.0 – feel free to open a PR!
