### ISSUE TITLE
cargo clippy --tests generates 9GB of warnings

### ISSUE THREAD

**Issue by guidorice** [georust/geo#398]
Relates to #394 

This massive output is mostly having to do with the formatting of literals in test fixtures. While there is nothing functionally wrong here, it does cause difficult developer experience particularly if you don't redirect the output to a file.

```bash
$ cargo clippy --tests > clippy.out 2>&1
$ ls -lh clippy.out 
Permissions Size User Date Modified Name
.rw-r--r--  9.5G alex 17 Nov  9:05  clippy.out
```
Cargo clippy can auto-fix some lints, when run on nightly. It might be good to explore that possibility.

active toolchain
----------------
stable-x86_64-apple-darwin (default)
rustc 1.39.0 (4560ea788 2019-11-04)

**Comment by frewsxcv** [comment]
We should maybe disable the clippy rules on our autogenerated files, a la `#![allow(clippy::unreadable_literal)]`

https://stackoverflow.com/questions/55402812/how-to-disable-a-clippy-lint-for-a-single-line-block

**Comment by frewsxcv** [comment]
Woops didn't mean to close

**Comment by frewsxcv** [comment]
done in https://github.com/georust/geo/pull/399
