### ISSUE TITLE
Use robust crate for orientation tests

### ISSUE THREAD

**Issue by urschrei** [georust/geo#415]
See previous discussion: #380,

We'll need to resolve the following issues around `num` and compatibility first: https://github.com/georust/robust/issues/3, https://github.com/georust/robust/issues/5

---

Update: this issue now tracks the progress in converting the algo. traits to use the robust predicates.

- [x] Kernel abstraction (#502)
- [x] Orient and WindingOrder (#502)
- [x] ConvexHull (#504)
- [x] ExtremePoints (#505)
- [x] Contains (#511)
- [x] Intersects (#511)

**Comment by frewsxcv** [comment]
Was this completed in https://github.com/georust/geo/pull/502? cc @rmanoka

**Comment by urschrei** [comment]
I _think_ we've got some instances left to track down, but need to have a careful look.

**Comment by rmanoka** [comment]
Yeah, we use it now for Winding and Orient traits.  Contains , Intersects are the prominent ones that need to use it yet.

**Comment by rmanoka** [comment]
Converting this issue into a tracker for making the existing traits use robust preds.
