### ISSUE TITLE
Fail on vincenty distance

### ISSUE THREAD

**Issue by incker** [georust/geo#418]
I am not expert in vincenty distance at all. And I was just testing how this functionality works, So I got a bug already on my second test. Code:

    let point1: Point<f64> = Point::new(0.0, 0.0);
    let point2: Point<f64> = Point::new(0.001, 0.0);
    let distance = point1.vincenty_distance(&point2).unwrap();

giving equal points will also give same error

    let point1: Point<f64> = Point::new(0.51, 88.1);
    let point2: Point<f64> = Point::new(0.51, 88.1);

The error:

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FailedToConvergeError'

Looks like it panics when distance is 0?
I am not sure, but looks like it is wrong behavior.
Forward thank you!

    geo = "0.12.2"
    rustc 1.43.0-nightly

**Comment by incker** [comment]
Thank you for reply.
But how mentioning that issue helps me?
I am not sure what to do. Have I close this issue and wait that pull request?

**Comment by frewsxcv** [comment]
Has anyone tested this on other vincenty implementations to see what the result is? That could be a good next step, finding out what the expected result is
