### ISSUE TITLE
FailedToConvergeError for vincenty_distance({0,0},{180,0})

### ISSUE THREAD

**Issue by brenzi** [georust/geo#425]
Vincenty fails ungracefully when asked to compute the distance between opposite aequatorial points:
{0,0},{180,0}

What I get is `FailedToConvergeError`. 
I think the function shouldn't panic in this case but just return a predefined value for that case.

**Comment by urschrei** [comment]
So if I understand correctly, Vincenty can fail for antipodal points (anything over ~19,936 km). The issue here is that we could provide the correct distance for your particular case, but not for all nearly-antipodal points, since that would require an additional distance calculation, and the whole point of Vincenty is that it's very cheap to calculate. I wonder whether it would be enough to check for _strictly_ antipodal points, which is [fast](https://mathworld.wolfram.com/AntipodalPoints.html) and then simply return the maximum possible Vincenty value.

**Comment by brenzi** [comment]
In that case I guess I can just apply error handling in my crate ;-) For such large distances I don't care about accuracy.

**Comment by frewsxcv** [comment]
Can anyone else confirm that other Vincenty implementations also error with these coordinates?

**Comment by michaelkirk** [comment]
I think there are two issues... we weren't correctly special casing equatorial points, so any equatorial points would fail to converge.  I opened a PR for that here: https://github.com/georust/geo/pull/438

But the antipodal thing, as I understand it, is strictly a limitation of vincenty. caveat is that I only just started studying vincenty a few hours ago, so i could be off base. 

In my short study, it seems like there are other options that don't have these shortcomings. In fact geopy has deprecated their vincenty implementation in favor of [geographiclib](https://geographiclib.sourceforge.io/html/python/index.html), which I believe calculates distance based on an implementation of the methods described in https://arxiv.org/pdf/1109.4448.pdf

**Comment by michaelkirk** [comment]
> In my short study, it seems like there are other options that don't have these shortcomings

related: https://github.com/georust/geo/issues/234

**Comment by michaelkirk** [comment]
> I think there are two issues... we weren't correctly special casing equatorial points, so any equatorial points would fail to converge. I opened a PR for that here: #438

Fixes here were merged in https://github.com/georust/geo/pull/438

> But the antipodal thing, as I understand it, is strictly a limitation of vincenty. 

In #440 we merged an implementation of the geodesic computation for distance, which, unlike vincenty, always converges.

From master, you can use it like this:
```rust
use geo::prelude::*;
use geo::Point;

// New York City
let p1 = Point::<f64>::from((-74.006, 40.7128));

// London
let p2 = Point::<f64>::from((-0.1278, 51.5074));

let distance = p1.geodesic_distance(&p2);

assert_eq!(
    5_585_234., // meters
    distance.round()
);
```
