### ISSUE TITLE
fixpoint geo feature

### ISSUE THREAD

**Issue by brenzi** [georust/geo#427]
I'd endorse a new feature `fixpoint32` to replace all `Float` with [FixedI32](https://docs.rs/fixed/0.5.4/fixed/struct.FixedI32.html). `geo-types` is already very generic and supports type arguments, so I wouldn't expect too much pain. `geo` would require a few feature gates though.....

* I guess trigonometry should be done with LUT's
* sqrt() requires some iterative method like [fpsqrt](https://github.com/chmike/fpsqrt/blob/a2f6c421a52b666e372b693b2a040f0ba8810154/fpsqrt.c#L112) does it.

I couldn't find ready-made rust libraries for this so far ([fpa](https://github.com/japaric/fpa) has a cordic, but no sqrt). Maybe port a [simple  c lib](https://sourceforge.net/p/fixedptc/code/ci/default/tree/fixedptc.h) for this case? Or something [fancier like libfixmath](https://github.com/PetteriAimonen/libfixmath)?

Would you welcome a PR or is this too off-topic?

**Comment by brenzi** [comment]
fixpoint math is on the way: 
https://github.com/japaric/fpa/pull/16

**Comment by urschrei** [comment]
`Float` covers both 32-bit and 64-bit floating point ops. I have no experience using fixed-point operations, so I'm a little confused:

1. How would your proposed feature allow us to retain double-precision ops?
2. Would switching to fixed-point for 32-bit ops give different results?
3. How would it affect current users of `geo` and `geo-types`? I.e. would it be a breaking change?
4. This sounds like a great deal of work. Who would implement it?

As I said, I don't have any experience with fixed-point ops, but as far as I can tell, this is a very niche use case, would be a lot of work for the implementor, and would cause significant disruption to existing users – in the absence of a _significantly_ more fleshed-out proposal that comprehensively answers the questions above, I can't imagine we would be interested. Depending on your use case, it may be more practical for you to re-implement the functionality you require in your own crate.

**Comment by brenzi** [comment]
I can understand your scepticism. 

To clarify: 
* fixpoint does impact precision and accuracy
* If done right, current users don't feel any difference. I'd just add a new optional feature 
* It is niche. I need havesine distance for a blockchain project, where fixpoint gives my the determinism that float can't provide. I'll code up what I need and if I see that the effort is reasonable, I might come up with a PR

**Comment by brenzi** [comment]
FYI: No PR planned. I wrote up just what I need:
https://github.com/encointer/pallet-encointer-currencies/blob/2779986cb6a3eeb308460be41df53b5f65728700/src/lib.rs#L190
using our own fork of `fixed` crate including transcendental functions: 
https://github.com/encointer/substrate-fixed

**Comment by frewsxcv** [comment]
Seems like the types provided in the `fixed` crates should implement the traits from `num_traits`, no?
