### ISSUE TITLE
Idea: Deprecate Area#area, and add Area#signed_area and Area#unsigned_area

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#460]
Thoughts? More verbose, but it makes it much clearer what the return value is.

Related to:

- https://github.com/georust/geo/issues/93
- https://github.com/georust/geo/issues/194#issuecomment-525304959
- https://github.com/georust/geo/issues/194#issuecomment-621477598

**Comment by urschrei** [comment]
Yes, absolutely!
