### ISSUE TITLE
Triangle.contains(Point) fails for degenerate triangles

### ISSUE THREAD

**Issue by msalib** [georust/geo#473]
Given a degenerate triangle  `t` where all coordinates are the same, `t.contains(p)` will return `true` for any Point `p`. 

I tried running this example:

```rust
use geo::prelude::*;
use geo::{Coordinate, Point, Triangle};

fn main() {
    let origin: Coordinate<f64> = (0., 0.).into();
    let tri = Triangle(origin, origin, origin);
    let pt: Point<f64> = (0., 1.23456).into();
    assert!(!tri.contains(&pt));
    println!("Hello, world!");
}
```

It fails with an assertion error, but it should pass.

One fix would be to include a check for degenerate self in the `contains` call; in that case, we should just return an equality check between any of the triangle's points (they're all the same) and `other`. Alternatively, perhaps the documentation could be updated to explain that degenerate Triangles are forbidden?

My rustc info is:
```
rustc 1.44.1 (c7087fe00 2020-06-17)
binary: rustc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.44.1
LLVM version: 9.0
```

Thanks so much for an excellent package! I only stumbled onto this because I've been building some spatial-join code using it and my property tests constructed this weird case.

**Comment by michaelkirk** [comment]
Fixed in #474
