### ISSUE TITLE
`Line.euclidean_distance(Polygon)` is incorrect

### ISSUE THREAD

**Issue by msalib** [georust/geo#476]
Here's an example program:
```rust
use geo::prelude::*;
use geo::{polygon, Coordinate, Line, Polygon};

fn main() {
    let line = Line::new(
        Coordinate {
            x: -0.17084137691985102,
            y: 0.8748085493016657,
        },
        Coordinate {
            x: -0.17084137691985102,
            y: 0.09858870312437906,
        },
    );
    let poly: Polygon<f64> = polygon![
        Coordinate {
            x: -0.10781391405721802,
            y: -0.15433610862574643,
        },
        Coordinate {
            x: -0.7855276236615211,
            y: 0.23694208404779793,
        },
        Coordinate {
            x: -0.7855276236615214,
            y: -0.5456143012992907,
        },
        Coordinate {
            x: -0.10781391405721802,
            y: -0.15433610862574643,
        },
    ];
    assert_eq!(line.euclidean_distance(&poly), 0.18752558079168907);
    println!("Hello, world!");
}
```

If you want to visualize what's going on and you have python+matplotlib+geopandas, you can run
```python
from shapely.wkt import loads
import geopandas as gpd

line = loads('LINESTRING (-0.170841376919851 0.09858870312437906, -0.170841376919851 0.8748085493016657)')
poly = loads('POLYGON ((-0.107813914057218 -0.1543361086257464, -0.7855276236615211 0.2369420840477979, -0.7855276236615214 -0.5456143012992907, -0.107813914057218 -0.1543361086257464))')
gpd.GeoSeries([line, poly]).plot()
```

I think the problem is located [here](https://github.com/georust/geo/blob/master/geo/src/algorithm/euclidean_distance.rs#L397): given a line, we are iterating over points in the polygon exterior rather than lines. Replacing `points_iter` with `lines` should fix it. That behavior matches the handling of holes on line 406. Note that the comments on lines 394 and 401 both refer to line-point distances, which seem wrong!

Since this is the second bug that my test harness has uncovered by accident, I thought I might share some details with you. My tests are property tests using the proptest crate. I've got some code to generate arbitrary Points, Lines, Polygons, Rects, Triangles, and LineStrings in a box. Then for a given operation (intersection, contains, euclidean distance), I compare the geo result with what I get from calling into libgeos from the geos crate (after converting my shapes into WKTs). I'll probably post the code in the next few days.

My rustc info is:
```rustc 1.44.1 (c7087fe00 2020-06-17)
binary: rustc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.44.1
LLVM version: 9.0
```

**Comment by urschrei** [comment]
Oof, yep that’s definitely wrong (also pretty sure it’s my bug). I’ll work on a fix tomorrow - as you say, should be pretty straightforward. Your test harness code sounds very useful - please let us know when you post it!

**Comment by msalib** [comment]
OK, you can see the proptest code [here](https://github.com/msalib/spatial-join/blob/master/src/proptests.rs#L134). Let me know if I can be of any help!
