### ISSUE TITLE
cannot borrow `*self` as immutable because it is also borrowed as mutable

### ISSUE THREAD

**Issue by kushwahashiv** [georust/geo#478]
I'm still getting error below via geo package.

https://github.com/rustsim/nalgebra/issues/616

what is the fix for this?

/Shiv

**Comment by urschrei** [comment]
Hi Shiv, could you be more specific about the error, and the program that causes it? Ideally, please post a minimal, reproducible version of the program and any supporting information (crates and crate versions etc), detailing the site of the error. Thanks!

**Comment by michaelkirk** [comment]
I'm going to close this for now since there's no response and it sounds like it's likely to be an error at the call site.
