### ISSUE TITLE
Iterate on Multipolygon without taking ownership

### ISSUE THREAD

**Issue by agersant** [georust/geo#486]
Hello!

As far as I can tell there is no way to iterate on the content of a `&Multipolygon`, other than cloning it. Ideally, an iterator on `&Multipolygon` would yield `&Polygon`.

If this is a simple oversight and easy to implement, I would be happy to be pointed in the right direction and make a PR.

Thanks!

**Comment by frewsxcv** [comment]
if you have a multipolygon, you should be able to do `multi_polygon.0.iter()` to create a borrowing iterator

**Comment by agersant** [comment]
Thank you!
