### ISSUE TITLE
Inconsistency between results of `closest_point` and `contains`

### ISSUE THREAD

**Issue by agersant** [georust/geo#488]
## Context
- `geo-types` version `0.6`
- `geo` version `0.14.1`
- Rust compiler `1.45.2`
- Tested on Windows 10

## Description

When calling `closest_point()` to project a point onto a triangular polygon, I would expect the resulting point to be considered part of the polygon. I am unsure if this is a bug or if the documentation for `contains()` needs to mention such caveats.

## Repro steps

The following code panics on the assertion:

```
let polygon = polygon![
  (x: 513.6569, y: 620.0),
  (x: 468.0, y: 574.3431),
  (x: 524.0, y: 580.0),
];

let point = point!(x:480.0, y:640.0);

if let Closest::SinglePoint(closest) = polygon.closest_point(&point) {
  dbg!(closest);
  assert!(polygon.contains(&closest));
}
```

**Comment by urschrei** [comment]
> I would expect the resulting point to be considered part of the polygon

This is inconsistent with the [DE9-IM](https://en.wikipedia.org/wiki/DE-9IM) model: a point on the boundary of a polygon is not contained by the polygon. You should be able to verify the same result using GEOS / Shapely / PostGIS, and Shapely can easily show you the relations using the [`relate`](https://shapely.readthedocs.io/en/latest/manual.html#object.relate) method.

I agree that we could more clearly document this, however; I tend to operate under the assumption that library users expect the DE9-IM model, and that's only true for those familiar with JTS-type libraries (as above), and this isn't necessarily the case for everyone.

**Comment by agersant** [comment]
Thanks for the clarification!
