### ISSUE TITLE
MapCoords on Rect panics if coords are inverted

### ISSUE THREAD

**Issue by rmanoka** [georust/geo#489]
`MapCoords` trait on `Rect` panics when we try to transform coords that invert the axes.  The reason is that `Rect::new` constructor expects min coords < max coords, and panics otherwise.  This leads to surprise panics, when using a `Geoemetry` enum which may be a `Rect`.  

While, this is a fairly minor issue, such transforms are fairly common in GIS use-cases:  for instance, when converting between "world" coordinates, and "image" coordinates of a geo-referenced GDAL raster.   It would be nice to check and swap min-max in the `MapCoords` and related trait impls for `Rect`.   PR available, if you would like to merge.

**Comment by urschrei** [comment]
Ah, great catch. Was this from a property-based test? PR is merged!

**Comment by rmanoka** [comment]
Hit this in one of our use-cases:  project a chunk of raster pixels to world coordinates during some processing.

Looks like I missed a few existing tests, that specifically tested the old behavior.

**Comment by michaelkirk** [comment]
> Looks like I missed a few existing tests, that specifically tested the old behavior.

FYI fixed in #492
