### ISSUE TITLE
Create a fuzz target to test correctness of rust-geo algorithms

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#527]
Steps:

1. Implement the [`Arbitrary`](https://docs.rs/arbitrary/0.4.7/arbitrary/trait.Arbitrary.html) trait for `geo::Geometry` so we can generate arbitrary geometries from a byte slice
1. Create a new cargo-fuzz project
1. Add geo and gdal as dependencies
1. For each fuzz iteration:
    1. Generate identical geometries for geo and gdal
    1. Perform operations on both geometries using geo and gdal algorithms
    1. Ensure the outputs of the algorithms are identical

**Comment by michaelkirk** [comment]
Love this idea!

**Comment by frewsxcv** [comment]
First fuzz target was added in https://github.com/georust/geo/commit/1e36d1e07bd7b83b6132940c66ebedb6204c3c8e
