### ISSUE TITLE
Add ConcaveHull generic implementation for any type that implement CoordsIter

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#543]
Once #542 is done, we can replace our ConcaveHull implementations with a generic one for any type that implements CoordsIter (using `exterior_coords_iter`). We should benchmark it to make sure it doesn't run any slower. We might be able to do something similar for other algorithms, like BoundingRect.

**Comment by michaelkirk** [comment]
Unblocked, since #542 is complete.

**Comment by frewsxcv** [comment]
Done in https://github.com/georust/geo/pull/889
