### ISSUE TITLE
Implement ClosestPoint for Geometry

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#544]
We already have ClosestPoint implemented for most geometry types, so let's implement it for the `Geometry` enum

**Comment by michaelkirk** [comment]
> I'd like to take a crack at this. Is the basic idea to add an impl for the Geometry enum under geo/src/algorithm/contains/geometry.rs?

Yep, that's the idea!

> I'm not very familiar with macros, but would something like make sense?

You can use `geometry_delegate_impl!` if it's helpful.  I think it would look something more like:
```
impl<F: GeoFloat> ClosestPoint<F> for Geometry<F> {
    crate::geometry_delegate_impl! {
        fn closest_point(&self, p: &Point<F>) -> Closest<F>;
    }
}
````

In any case, you'll have to make sure that all the inner variants of Geometry `impl ClosestPoint`. I believe most do, but haven't checked that all of them do.

See also the [`geometry_delegate_impl` documentation](https://github.com/georust/geo/blob/master/geo/src/types.rs#L40)

And an example of how it's used elsewhere in geo: https://github.com/georust/geo/blob/master/geo/src/algorithm/bounding_rect.rs#L157

**Comment by pkopparla** [comment]
Thank you @michaelkirk !
I've added implementations for Triangle, Rectangle, GeometryCollection and Geometry. I'm still a little confused on how the latter two work, it feels like GeometryCollection and Geometry have a circular dependency on each other. But I will make a pull request now so you guys can have a look.

**Comment by callpraths** [comment]
I think this issue can be closed. #675 addressed both `Geometry` and `GeometryCollection`:

https://docs.rs/geo/latest/geo/enum.Geometry.html#impl-ClosestPoint%3CF%2C%20Point%3CF%3E%3E
https://docs.rs/geo/latest/geo/struct.GeometryCollection.html#impl-ClosestPoint%3CF%2C%20Point%3CF%3E%3E

I don't think there's any more work left here.

**Comment by michaelkirk** [comment]
Indeed, thanks!
