### ISSUE TITLE
approx: Increase the minor version number

### ISSUE THREAD

**Issue by martinfrances107** [georust/geo#550]
Looking at the packages in 

geo-types/Cargo.toml

approx should be increased from 0.3.0 to 0.4.0 to reflect the latest minor release.

locally I can say tests pass...I am about to generate a PR

**Comment by michaelkirk** [comment]
Resolved in #551 (thanks!)

GitHub Issues work best if you want to discuss something before/while working on it, or if you want to report something that you're not planning to work on. 

But don't feel like you are required to make a separate issue when you already have a PR ready to go - we can just discuss things in the PR and avoid the extra cleanup and avoid the risk of split discussions.
