### ISSUE TITLE
Clippy: Don't call into_iter() on types that support iter()

### ISSUE THREAD

**Issue by martinfrances107** [georust/geo#553]
I just notices this clippy warning being generated on our code

here is the link to the clippy documentation.

[clippy warning](https://rust-lang.github.io/rust-clippy/master/index.html#into_iter_on_ref)

If the type support iter() then we should call it directly.

we have this in 6 places.

I am about to upload my PR

**Comment by michaelkirk** [comment]
Fixed in #554
