### ISSUE TITLE
Clippy: Remove redundant import statement 

### ISSUE THREAD

**Issue by martinfrances107** [georust/geo#556]
Just picking off a trivial clippy warning 

We can remove a 'use' statment 

I am about to generate a single line PR

`warning: this import is redundant
 --> geo-postgis/src/from_postgis.rs:5:1
  |
5 | use postgis;
  | ^^^^^^^^^^^^ help: remove it entirely
  |
  = note: `#[warn(clippy::single_component_path_imports)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports
`

**Comment by frewsxcv** [comment]
resolved in #557
