### ISSUE TITLE
clippy in CI?

### ISSUE THREAD

**Issue by michaelkirk** [georust/geo#558]
All of @martinfrances107's recent PR's have got me wondering if we should incorporate clippy into our CI.

What do you think?

And if we did incorporate, should it *fail* CI or just be a warning? 

IIRC @urschrei pointed out elsewhere that sometimes these kinds of hurdles can be off-putting to new contributors who aren't already familiar with the large variety of tools.

**Comment by urschrei** [comment]
Ah, yep, big fan of Clippy _warning_ on CI, for exactly the reason above.

**Comment by frewsxcv** [comment]
+1 for warning, +0 for failing

**Comment by martinfrances107** [comment]
There are 20 or so clippy warnings with the project ... 

I will generate a new PR to fix them 

Just a little warning  there is are lots of warnings but one I suggest we ignore

#[allow(needless_resturn)]

This project has lots of instances of 

return(x);

which I think is perfectly reasonable, but clippy will tell you that is is not idiomatic enough.

**Comment by martinfrances107** [comment]
In the review of the PR 

[Followup ](https://github.com/georust/geo/pull/559#discussion_r536938856)

That given `return A `

We should follow the rust specific idom, dropping both the return and the semicolon.

This is contraversial and makes the blood boil of some C programmer I know
but hey I am going to follow the convention.

I am about to submit a new PR

Finally

"**Should we also follow up with a git hook that rejects  PRs with clippy warning?**"

**Comment by martinfrances107** [comment]
Here is the followup PR

https://github.com/georust/geo/pull/560

**Comment by michaelkirk** [comment]
> Should we also follow up with a git hook that rejects PRs with clippy warning?

I'm not sure what you mean by "git hook" in this context. Assuming you mean something like: https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks - I'm pretty sure GitHub doesn't support server side hooks.

The closest I think we have to server-side enforcement is what I'm proposing here - to add something to our GitHub action workflow. 

It seems like most people would rather not *reject* a PR outright for clippy violations. The thinking being that it may discourage new contributors, but rather just print the warnings.

In addition to that though - you've got me thinking - I'd personally like to have a client-side git-hook to run clippy on commit. Shipping a "blessed" set of git hooks and documentation in the repository which can be quickly installed on the developer's machine might be worthwhile.

**Comment by martinfrances107** [comment]
Sorry for letting this conversation become stale...

In terms of adding to our github action work flow ...

Here is a quote from the description of the  [rust-clippy-check](https://github.com/marketplace/actions/rust-clippy-check) action.


> This GitHub Action executes clippy and posts all lints as annotations for the pushed commit, as in the live example here.

I will try it out this weekend on a separate project  and report back..

**Comment by martinfrances107** [comment]
I looked at the module ... what the module does not do is evaluate any PR 

It just reports the state of a branch.. after the fact. So I want to wait for a better solution.
