### ISSUE TITLE
Add WKT to devDependencies for test fixtures

### ISSUE THREAD

**Issue by michaelkirk** [georust/geo#566]
When testing, we'll often define inline simple geometries of a few points or lines. But for testing more geometries, we conventionally stick them in our test_fixtures:
https://github.com/georust/geo/blob/master/geo/src/algorithm/test_fixtures

Rather than writing fixtures as rust code, I think it would be better to store them in a format like WKT. As well as being able to read, it makes it easier to share tests with external projects / reference implementations.

WDYT?

So, todo:

- [ ] add WKT dep
- [ ] convert test fixtures to wkt

**Comment by frewsxcv** [comment]
storing them in wkt instead of rust vecs sounds good to me!
