### ISSUE TITLE
Proposal: Flatten algorithm module layout

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#572]
# Current layout

Currently, whenever we add an algorithm to `geo`, we create a new module in the `crate::algorithm` module. Within that new module, we have all the necessary structures and traits to utilize the new algorithm. This new module also gets reexported at the top-level of the crate. Visualized, this looks like:

![Untitled Diagram(5)](https://user-images.githubusercontent.com/416575/102643084-b7072f80-412c-11eb-852e-0ce88d95f6df.png)

Effectively, our users have two ways to import algorithms in their crate:

```rust
use geo::algorithm::winding_order::Winding;
// or
use geo::winding_order::Winding;
```

Subjectively, my view is this structure is unnecessarily deep, and requires a lot of typing and knowledge about our module layout just to import a single trait.

# History

The `crate::algorithm` module dates back to May 2016 when [`Centroid`, our first algorithm, was implemented in the crate](https://github.com/georust/geo/pull/24). I don't recall us ever having a discussion about module layout, so I'm going to assume there's not much history beyond this!

# Proposed layout

I propose all traits for algorithms live at the root of the crate. Any supporting structures for the trait can live in a submodule specific to that algorithm. Visualized, this looks like:

![Untitled Diagram(8)](https://user-images.githubusercontent.com/416575/102652043-7a8f0000-413b-11eb-882a-cf0ff5436410.png)

An example

As a point of comparison, this is similar to how `HashMap` and other collections are laid out in the standard library:

![Untitled Diagram(7)](https://user-images.githubusercontent.com/416575/102651873-474c7100-413b-11eb-84f6-2ac5464054e1.png)

The biggest downside to this is the docs for root of the `geo` crate will get much bigger. I think this can be addressed by having an organized index in the docs of everything at the crate root:

```rust
//! The `geo` crate provides and geospatial primitives and algorithms.
//!
//! # Types
//!
//! - `Coordinate`: ...
//! - `Point`: ...
//!
//! # Algorithms
//!
//! - `BoundingRect`: ...
//!
//! ## Distance
//!
//! - `EuclideanDistance`: ...
```

What does everyone think?

**Comment by michaelkirk** [comment]
Maybe the `algorithms` module made sense back when `geo` and `geo-types` were a single crate. After cleaving off geo-types pretty much everything in `geo` is related to the algorithm module.

I think the more that functionality is tucked into traits, the more challenging it is to find functionality in the docs. I don't have a proposed solution for that. But I think your proposal makes sense and will be an improvement.

Do you have a plan to deprecate the old import paths?

**Comment by frewsxcv** [comment]
I just opened a draft pull request: https://github.com/georust/geo/pull/576

The remaining work is building out the crate index documentation. Once I finish that, I may pull the documentation out into a separate pull request just to make the changes a little smaller
