### ISSUE TITLE
Should rotating caliper "leftturn" function be replaced with robust orientation check?

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#588]
Should this:

https://github.com/georust/geo/blob/5a85dde4ff5d26e03c8ba15261dc8974745eeac8/geo/src/algorithm/polygon_distance_fast_path.rs#L399-L412

Be replaced with:

https://github.com/georust/geo/blob/5a85dde4ff5d26e03c8ba15261dc8974745eeac8/geo/src/algorithm/kernels/mod.rs#L14-L25

**Comment by urschrei** [comment]
Yep – I've replaced it in a WIP branch (no effect on the current failure though 😭)

**Comment by frewsxcv** [comment]
Rotating calipers was removed in https://github.com/georust/geo/pull/920
