### ISSUE TITLE
LineString add  a is_cyclic_match() function.

### ISSUE THREAD

**Issue by martinfrances107** [georust/geo#590]
I have a algorithm which stores points in a hashmap which is then 'drained' in a function that constructs a new closed geo::Linestring.

By drained I mean read out in an order,  that because of hashing,  changes for every run.

What I need is a to be able to assert equality for 2 closed 'LineString's. p and q

p has points A, B, C, D, E in that order 
q has points D, E, A, B, C or in any other cyclically consistent order.

I am about to develop this function .. might as well do it in here.

The message signature 

where A, B, C, D, E are geo::Point<T>

let a = LineString::from(vec![A, B, C, D, E]);
let b = LineString::from(vec![D, E, A, B, C]);
assert!(a.is_cyclic_match(&b));

The new method will have docs doctests etc 

Anyway I am going to develop this algorithm

**Comment by michaelkirk** [comment]
This seems useful!

Does it work for non-closed linestrings?

e.g. does this pass?
```
let a = LineString::from(vec![A, B, C]);
let b = LineString::from(vec![A, B, C]);
assert!(a.is_cyclic_match(&b));
```

I'm wondering if the semantics are strictly "is_a_cycle && matches".

Mathematically, I don't think there's really a notion of "first" vs "last" point for a Ring, it's only an artifact of how it's commonly encoded. In my mind what you're doing could be described as "comparing two LinearRings for equivalence".

However, I was sort of surprised to see that JTS/GEOS would not consider two such LinearRings equivalent and am not aware of a method to make such a comparison. If one did exist, it'd be good to copy their naming conventions so people coming from other environments know what to look for.

**Comment by urschrei** [comment]
> In my mind what you're doing could be described as "comparing two LinearRings for equivalence".

I had the same thought. Isn't this a stable sort on the x coordinates and y coordinates of each, followed by a comparison?

The lack of equivalence in JTS / GEOS is really surprising – I suspect there's reason for it, as opposed to oversight.

**Comment by michaelkirk** [comment]
> The lack of equivalence in JTS / GEOS is really surprising – I suspect there's reason for it, as opposed to oversight.

To be clear, some method might exist somewhere, I'm not very familiar with the whole catalog, but yes there's no special isEqual implementation for LinearRing, meaning it inherits the implementation from LineString...

Here's the LineString `equalsExact` (which is maybe an intentionally specific name):
jts: https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/geom/LineString.java#L217
geos: https://github.com/libgeos/geos/blob/master/src/geom/LineString.cpp#L263

**Comment by michaelkirk** [comment]
Looking into things a bit more...

I suspect this is actually implemented here in Geometry:

```
  public boolean equals(Geometry g) {
    if (g == null) return false;
    return equalsTopo(g);
  }
```
The equalsTopo method:
```
  public boolean equalsTopo(Geometry g)
  {
    // short-circuit test
    if (! getEnvelopeInternal().equals(g.getEnvelopeInternal()))
      return false;
    return relate(g).isEquals(getDimension(), g.getDimension());
  }
```

Which depends on the DE-9IM stuff I've been working on #515... It's been quiet lately, but I intend to pick it back up next week!

**Comment by martinfrances107** [comment]
Thank you all for looking at this ...

Just to answer a couple of questions 

I was thinking that two open LinesStrings ... equal in every other respect would return FALSE

so at the top of the method I have now partially implemented is this "return early" bolier-plate.

```
        if !self.is_closed() || !rhs.is_closed() {
            return false;
        }

        if self.coords_count() != rhs.coords_count() {
            return false;
        }
```

both your comments about linear ring equivalence are correct ... I just wanted to state the problem simply and completely without scaring any reader away..

One further comments given the recent work on comparing points and there being two comparison standards ... In the is_cyclic_match() function  I  was planning on providing to "relative_eq" comparison operator by default allowing for the programmer to override with a absDiffEq() comparison operator .. if that makes sense 

I will stop what I am doing and read up on the other issue and help out where I am able.

Also I am already considering my need for an  additional geo_types::Polygon  ring equivalence check.

Where 

A) The exterior rings could be checked for cyclic match.

B) To be cyclically equal each interior  LineString  needs to be paired with a matching LineSting 
in the polygon under test.

I think step B is going to explode into a moderately complex bit of code.

**Comment by michaelkirk** [comment]
> I was thinking that two open LinesStrings ... equal in every other respect would return FALSE

Makes sense to me!

> I think step B is going to explode into a moderately complex bit of code.

This should all be covered by #515... once I finish it. 🥵  

I have a very rough wip branch here: https://github.com/georust/geo/tree/mkirk/geomgraph

I certainly don't want to slow you down or stop you from contributing, but be aware that if you do the work and get it merged, it might soon be deprecated and removed once (and if) the geometry graph based approach is merged.

**Comment by martinfrances107** [comment]
> This will all be covered by #515

Ok -- The spatial indexing should be invariant - between two closed Linstring which are cyclic twins.

I don't think my intermediate code .. is worth reviewing and making into library grade code.
but I am making a version public its all in one file cyclic_match.rs

https://github.com/martinfrances107/geo/blob/cyclic_match/geo/src/algorithm/cyclic_match.rs

It may be of use as a set of testcases.

#[cfg(test)]
mod tests {
    use super::*;

    use geo_types::Coordinate;
    use geo_types::LineString;

    const A: Coordinate<f64> = Coordinate { x: 0., y: 0. };
    const B: Coordinate<f64> = Coordinate { x: 0., y: 10. };
    const C: Coordinate<f64> = Coordinate { x: 10., y: 10. };
    const D: Coordinate<f64> = Coordinate { x: 0., y: 10. };
    const E: Coordinate<f64> = Coordinate { x: 0.5, y: 0.5 };
    #[test]
    fn test_cyclic_match() {
        let mut ls_x = LineString(vec![A, B, C, D]);
        ls_x.close();
        let mut ls_y = LineString(vec![C, D, A, B]);
        ls_y.close();

        assert!(ls_x.is_cyclic_match(ls_x.clone()));
        assert!(ls_x.is_cyclic_match(ls_y));

        let one_less = LineString(vec![A, B, C]);
        assert!(!ls_x.is_cyclic_match(one_less));

        let one_more = LineString(vec![A, B, C, D, E]);
        assert!(!ls_x.is_cyclic_match(one_more));

        let a_cyclic = LineString(vec![A, D, C, B]);
        assert!(!ls_x.is_cyclic_match(a_cyclic));
    }

Thanks for all the comments I will close this in a few days.

**Comment by rmanoka** [comment]
Adding to what Michael and Stephan have mentioned above:  we do have an implementation of Linestring contained in another LineString, so a slightly round about way would be:  `ls1.contains(&ls2) && ls2.contains(&ls1)` .  I think this is also how DE9IM defines equivalence of two geometries.  Note that this will accept more than strict equality of the coords with possible shifts, so it is true even if one of the geometries has additional "dummy" points along one of its segments.

Another options is to use [`utils::least_index`](https://github.com/georust/geo/blob/master/geo/src/utils.rs#L97) to get you the index of the lexicographically least point each of the linestrings, and then iterate from those indices, to verify equality.  Unfortunately, you may run into some issues if the least point is repeated in the linestrings.  Also, I believe the function is currently `pub(crate)`.

**Comment by martinfrances107** [comment]
@rmanoka, thank you .. that was a really useful set of things .. I was not considering 

>Unfortunately, you may run into some issues if the least point is repeated in the linestrings

I am thinking about machine generated lines strings .. so an output of 1000 points in which say 5 might be so close together that they are considered identical .. within the 'epsilon box' boundary of one another.... 

So I am worried about the repeated point problem ...  and that may explain why I used such a computationally inefficient algorithm.

Also at some point if the linestring comes back very close to itself but does not touch  ... I think any comparison test will fail.

PS In what  I made public  I just used a straight comparison of floats... I did not use the relative_eq branch which all this code intended to work in  with .. only because it is not canonical yet.

**Comment by rmanoka** [comment]
Yeah, the techniques I've suggested above only check for exact equality in which case repeated points is slightly easier to handle.  

For approx equality, you'll need to define what's the notion of equivalence you're looking for.  Another common notion (eg. used my ML / object detection community) is the IOU of area enclosed.  That is, area of intersection over area of union of the two regions. This can be computed using the geo_booleanop crate.  If this value (always <= 1) is close to 1, you can consider it as equivalent.

**Comment by martinfrances107** [comment]
Thank you all for shaping my thinking on this issue, I think this issue should be closed.

This morning I find my self giggling  into my cornflakes.

I am going through the growing pains of stitching several open source libraries into something from which I can make my application 

I have a lot of love for this rust crate

https://github.com/mourner/delaunator-rs

An whilst reading their source code I saw this 

https://github.com/mourner/delaunator-rs/blob/master/src/lib.rs

```
    fn nearly_equals(&self, p: &Self) -> bool {
        (self.x - p.x).abs() <= EPSILON && (self.y - p.y).abs() <= EPSILON
    }
```

Oh well each project is wresting with these problems.

Thank you all again.

**Comment by michaelkirk** [comment]
Go ye fourth and spread the gospel of Best Practice in Floating Point Comparison! 🙌
