### ISSUE TITLE
Deprecation notice is not 'semver' compliant

### ISSUE THREAD

**Issue by martinfrances107** [georust/geo#609]
When I run cargo clippy on the project today ... all is clean

BUT 

When I run clippy on a third party module with geo as a dependency. Specifically one  that needs updating due to the recent changes involving CoordFloat and CoordNum then I see this warning about the incorrect formatting of a semi version number.

We need "0.7.0" instead of "0.7"

I am about to generate a one line PR.

```
error: the since field must contain a semver-compliant version
  --> /home/martin/build/geo/geo-types/src/lib.rs:52:14
   |
52 | #[deprecated(since = "0.7", note = "use `CoordFloat` or `CoordNum` instead")]
   |              ^^^^^^^^^^^^^
   |
   = note: `#[deny(clippy::deprecated_semver)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#deprecated_semver
```

**Comment by michaelkirk** [comment]
Fixed in #610 - thanks @martinfrances107!
