### ISSUE TITLE
Trait Contains seems to fail for simple linestring.contains(&linestring)

### ISSUE THREAD

**Issue by Nevsden** [georust/geo#615]
I made two non-intersecting squares, which are oriented ccw around the origin, one with span of `1.0` and one with span of `10.0`.

```rust 
fn rect(diameter: f32) -> LineString<f32> {
    let rect = line_string![
        (x: -diameter / 2., y: -diameter / 2.),
        (x: diameter / 2., y: -diameter / 2.),
        (x: diameter / 2., y: diameter / 2.),
        (x: -diameter / 2., y: diameter / 2.),
        (x: -diameter / 2., y: -diameter / 2.),
    ];

    rect
}
```
The `. contains()` method on these two squares returns a `false` if the containment of the smaller square inside the bigger one is tested.

```rust 
fn main() {
    let little = rect(1.0);
    let big = rect(10.0);
    println!("{}", big.contains(&little));
}
```
```text
false
```

However if the bigger `LineString` is firstly converted into a `Polygon`, the result of the containment trait is `true`.

```rust
fn main() {
    let little = rect(1.0);
    let big = rect(10.0);
    let poly = Polygon::new(big, vec![]);
    println!("{}", poly.contains(&little));
}
```
```text
true
```

Is this behaviour intentional or have I found a bug? I am curios because I tend to misinterpret this library often (having already misinterpreted the `geo-clipper` trait a week earlier)

**Comment by Nevsden** [comment]
I tried to understand the intented behaviour of the containment method on two `LineString` objects from the [test implementation](https://github.com/georust/geo/blob/5ac0b48c2a768acd1d769e11646563978d9250a9/geo/src/algorithm/contains/mod.rs#L348). If I understood it correctly, a `LineString` will not test another `LineString` for being inside oneself (speaking of the behaviour of a `Polygon`), assuming that oneself is closed, but will rather test, if the other `LineString` lies completely **on oneself**.

**Comment by rmanoka** [comment]
Yes, that is the intended behaviour.  As per the OGC specs linked in the docs: `LineString` (closed or open) is defined as the one-dimensional set of points along the segments of the line.  `Polygon` is defined the 2-dimensional region enclosed by the linestring.

**Comment by Nevsden** [comment]
@rmanoka : Sweet! 
By the way I really love the work you guys put into this crate. Really appreciate it being a SE for CAM software myself.
