### ISSUE TITLE
Add impl to convert geometries to different CoordNum: e.g. Geometry<f32> -> Geometry<f64>

### ISSUE THREAD

**Issue by Nevsden** [georust/geo#617]
Defining traits on a type outside the crate which implements it is forbidden in rust. So another idea is born...

As far as I can see it, this crate does not have a function, which converts (or tries to convert) from an arbitrary type into an arbitrary type. This can be particularily useful, if e.g. converting from `LineString<f32>` to `LineString<f64>`. 

The crate `nalgebra` has such a [function](https://docs.rs/nalgebra/0.24.1/nalgebra/fn.convert.html), which can be pretty handy. It also solves the upper case.

**Comment by michaelkirk** [comment]
updated the title for clarify. Had to read the whole thing before I understood you weren't talking about, e.g. Converting a Rect to a Polygon.

**Comment by frewsxcv** [comment]
Similarly, I think we can also add these implementations for all geometry types:

- `impl<T, U> TryFrom<Point<T>> for Point<U> where U: TryFrom<T>`
- `impl<T, U> From<Point<T>> for Point<U> where U: From<T>`

**Comment by urschrei** [comment]
> - `impl<T, U> TryFrom<Point<T>> for Point<U> where U: TryFrom<T>`
> 
> - `impl<T, U> From<Point<T>> for Point<U> where U: From<T>`

Expressive type systems are a _delight_.

**Comment by Nevsden** [comment]
> updated the title for clarify. Had to read the whole thing before I understood you weren't talking about, e.g. Converting a Rect to a Polygon.

Thank you for updating. Makes much more sense now. Glad you could get the meaning from the contents of the issue at the very least.

**Comment by frewsxcv** [comment]
Do people feel this functionality should live in `geo` or is it "core" enough to include in `geo-type`?

**Comment by michaelkirk** [comment]
I'm OK with either, with a preference for putting it in geo-types.

**Comment by frewsxcv** [comment]
Oh actually, the `From` and `TryFrom` implementations _need_ to be in geo-types (assuming we want them), so I guess that answers my question

**Comment by michaelkirk** [comment]
😅  well great then.
