### ISSUE TITLE
Polylabel

### ISSUE THREAD

**Issue by urschrei** [georust/geo#65]
I've implemented the very nice Mapbox Polylabel algorithm for optimised polygon label placement, here: https://github.com/urschrei/polylabel-rs

I think it should be part of georust. If you agree, should it be:
- an `impl` on Polygon within `rust-geo`
  - Should it have the same name, or a different name?
- a separate crate, like `Polyline`

**Comment by frewsxcv** [comment]
Sorry for the delay, but busy recently. In my opinion, I think this algorithm is specific enough that it should probably live in a separate crate. My thinking is that rust-geo should only contain the core primitive algorithms that other crates can build on top of. What do you think? If you're wanting to move the crate to the GeoRust organization (you don't have to if you don't want to), feel free to do so. Nice job by the way, that crate looks great :)
