### ISSUE TITLE
NaN and inaccuracies in distance functions

### ISSUE THREAD

**Issue by samtay** [georust/geo#650]
Initially I was using `haversine_distance`, but I noticed it gave very incorrect measurements, namely that the distance from `37.85814, -81.09902` to `25.137212, -80.938773` is only ~ 137 miles.

So I just switched to `geodesic_distance` after reading in the GH issues that it is more accurate. However, it returns NaN for almost all inputs. Furthermore, it also calculates the incorrect ~ 137 miles:

```rust
use geo::prelude::*;
use geo::{point, Point};

fn main() -> () {
    const MILES_PER_METER: f64 = 0.000621371;
    // Nan example
    let p1 = point!(x: 36.266, y: -117.19);
    let p2 = point!(x: 35.97, y: -92.89);
    println!("geo: {:?}", p1.geodesic_distance(&p2));
    println!("haver: {:?}", p1.haversine_distance(&p2));

    // Inaccuracy example
    let p1 = point!(x: 37.85814, y: -81.09902);
    let p2 = point!(x: 25.137212, y: -80.938773);
    println!("geo: {:?}", p1.geodesic_distance(&p2) * MILES_PER_METER);
    println!("haver: {:?}", p1.haversine_distance(&p2) * MILES_PER_METER);
}
```
outputs
```
geo: NaN
haver: 2702045.209410351
geo: 137.9805390357987
haver: 137.37565388503617
```
The route on [google maps](https://www.google.com/search?q=directions+from+37.85814%2C-81.099+to+25.1372%2C-80.939&client=firefox-b-1-d&ei=ps-uYI2WFseSwbkPnbSzkA4&oq=directions+from+37.85814%2C-81.099+to+25.1372%2C-80.939) is a straight shot and over 1000 miles.
I'm on `geo 0.18.0`. Am I missing something?

**Comment by michaelkirk** [comment]
It looks like you've got your lat (y) / lon (x) mixed up.

Can you please confirm and let me know how it goes after flipping?

**Comment by samtay** [comment]
Omg :blush: sorry! I just assumed lat before lon, my bad. Yes, everything's working as expected after flipping.

**Comment by michaelkirk** [comment]
You certainly are not the first person to make that mistake. Have a good day!
