### ISSUE TITLE
Please stop using postgis crate it's unsound

### ISSUE THREAD

**Issue by a1ien** [georust/geo#663]
It have critical unsafe usage as described in https://github.com/andelf/rust-postgis/issues/27
They use unsound `unsafe { *mem::transmute::<_, *const f64>(self) }` 
And it looks like the author of this crate is not going to fix it.

**Comment by lnicola** [comment]
Let's try fixing andelf/rust-postgis#27 before doing anything like this.

**Comment by a1ien** [comment]
Yes. If it's fixed it's also ok. But there was no reaction to my message for over a year

**Comment by a1ien** [comment]
If not fixed maybe it's worth to fork and maintain in georust?

**Comment by urschrei** [comment]
It looks like @pka has commit access here…

**Comment by pka** [comment]
Merged https://github.com/andelf/rust-postgis/pull/31 and made a new release. Thanks @lnicola !
