### ISSUE TITLE
Incorrectly comparing floats causes random test failings

### ISSUE THREAD

**Issue by martinfrances107** [georust/geo#666]
We are experiencing random test failings [random fail](https://github.com/georust/geo/pull/665#issuecomment-942024160)

we developed a solution #565 

The solution is to consistently apply our unspoken policy of use assert_relative_eq!() where possible.

I am working on a PR.

**Comment by martinfrances107** [comment]
#667

This PR is a scan of the map_coords.rs files.. picking up all the problem comparision that I could see.

**Comment by lnicola** [comment]
I think there are other places where this is done, so I'm not sure it's fully fixed.
