### ISSUE TITLE
Export abs_diff_eq!() etc for use outside testing

### ISSUE THREAD

**Issue by martinfrances107** [georust/geo#670]
Recently we added the facility to compare floating point numbers, into test

for example 

assert_relative_eq!(centroid, point!(x: 5.5, y: 2.5518518518518523));

There was an oversite on my part.. it only works in test environments.

I want to add an additional feature, named "use-approx" 

So that in my third party crate's Cargo.toml if I specify
```
[dependencies]
geo={"0.18.0", features=["use-approx"] }
```

Then I can now do this in production code.

```
let a = Coordinate { x: 1.0_f64, y: 2_f64 };
let b = Coordinate { x: 3.0_f64, y: 4_f64 };
if a.abs_diff_eq(&b) {
  // do something
} 
```

This new feature needs an entry in the CHANGES.md file 
 
here is the text I propose.

```
* New Feaure 'use-approx' exports the implementation of the traits AbsDiffEq and RelativeEq
  for various geometry types, for use in third party crates.
```

I am just about to  push a PR.

**Comment by michaelkirk** [comment]
I'm going to close this since it's sat here for a while without response from @martinfrances107.

Feel free to explain and we can re-open it.
