### ISSUE TITLE
Leftover Travis CI references

### ISSUE THREAD

**Issue by atouchet** [georust/geo#690]
Travis CI support was removed in #469 but there are still a few references left:

https://github.com/georust/geo/blob/e6bfce6d4583ba105cd509ced1de2070effe0057/README.md#L3

https://github.com/georust/geo/blob/25dd3933dc7303d4f30b1dbca6ba9ad75fd087ce/geo/Cargo.toml#L15

**Comment by michaelkirk** [comment]
Thanks for bringing this up, I've pushed a commit to delete these. 

https://github.com/georust/geo/commit/4b3a7e92ca84fc35bf02ef7c4c674358ab0f3eb6

(I pushed directly since it didn't seem worth a PR. Fellow reviewers, LMK and I can be more conservative in the future.)
