### ISSUE TITLE
serde is not supported for `Geometry` and `GeometryCollection`

### ISSUE THREAD

**Issue by msalib** [georust/geo#702]
Serializing one of those doesn't work because there is no `#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]` for either of those types.

**Comment by martinfrances107** [comment]
+1 I think this need to be made complete.

When I first saw it, a month ago I was in a rush and did not have time to fix it upstream ...here 

The ugly workaround I used was to loop over geometry colections inner elements and serialize/deserialise each element individually ...

I would be happy to help out here...

**Comment by martinfrances107** [comment]
So I have created an initial patch ... testing is on my mind. Geometry primitives like point do not have explicit testing for serde. So I am not sure how to fit in testing?

**Comment by frewsxcv** [comment]
Done in #704
