### ISSUE TITLE
Add `num_rings` or `rings_count` to `Polygon`

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#706]

**Comment by callpraths** [comment]
Thanks for adding starter bugs for the likes of me :)
Is there interest in adding this?

A few clarifications would be useful:

1. Naming: I'd vote for `ring_count` to go with existing `coord_count` (PostGIS uses `ST_NRings`, geos crate has `get_num_interior_rings` and nothing that includes the exterior ring).
2. Should this be added directly to struct impl(s)?
3. It should probably be added to: `Polygon`, `MultiPolygon`, `Rect` (always 1) and `Triangle` (always 1).

**Comment by callpraths** [comment]
I want to answer 2 with: Add `geo::algorithm::RingCount` trait, even though it will only be implemented for a few of the core types. There are plenty of examples where algorithms only apply to subset of types (e.g. `FrechetDistance` only applies to `LineString`.

**Comment by frewsxcv** [comment]
Resolved in https://github.com/georust/geo/pull/1145
