### ISSUE TITLE
Add `num_coords` or `coords_count` to `Polygon`

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#707]
https://github.com/georust/geo/pull/701#discussion_r776820474

**Comment by callpraths** [comment]
Thank you for filing low hanging fruits for folks looking to get their feet wet.

I think this one already exists: https://docs.rs/geo/latest/geo/struct.Polygon.html#method.coords_count

**Comment by michaelkirk** [comment]
Thanks for noticing!
