### ISSUE TITLE
Missing geometric algorithms

### ISSUE THREAD

**Issue by stijn-ucrowds** [georust/geo#712]
Hi, I'm currently working on making our Rust application compile to wasm32-unknown-unknown which entails getting rid of any C++ dependencies. I have managed to replace the Boost Voronoi with the excellent [boostvoronoi.rs](https://github.com/eadf/boostvoronoi.rs), but I have not yet found replacements for the following functionality from Boost Geometry:

- Calculating the non-overlapping set of line segments
- Boolean operations on sets of polygons (union, difference/not, non overlapping set)

These seem like a good fit for the geo library, but I didn't manage to find them in the library (perhaps I'm missing something). Are there any other crates that implement this functionality ([geo-booleanop
](https://crates.io/crates/geo-booleanop) seemed promising, but it was supposedly buggy and not maintained). Thank you.

**Comment by michaelkirk** [comment]
related #620

Short answer: as far as I know, geo-booleanop is the best pure rust solution that I know of.

Also related #80, #81,

**Comment by michaelkirk** [comment]
I think this was more of a support request, so I'm going to close this now that it's been answered.

It seems like if there were an implicit feature request in there, it's covered by the aforementioned issues.
