### ISSUE TITLE
Quality of life ergonomics, like `point += other_point`, and `point!(x, y)` without the extra `x: ` labels

### ISSUE THREAD

**Issue by willhansen** [georust/geo#713]
I'm half convinced that I'm missing some really obvious ways to do these things, but I'm baffled that I'm having to make utility functions for them instead of having them built in.

A 2d point is _literally_ the example for the std::ops::AddAssign trait.  https://doc.rust-lang.org/std/ops/trait.AddAssign.html

**Comment by frewsxcv** [comment]
I'm hesitant to remove the `x:` and `y:` labels because of https://macwright.com/lonlat/. It's only a few extra characters and removes ambiguity.

**Comment by michaelkirk** [comment]
> point!(x, y) without the extra x: labels

I agree with @frewsxcv about keeping the labels. They weren't required by accident. 

I'm going to close this, but we can re-open if there proves to be strong support for it.

And the AddAssign, et al PR (https://github.com/georust/geo/pull/715) is merged, thank you for that!
