### ISSUE TITLE
Annotate `#[must_use]` on all algorithms that return `Result`

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#716]
e.g. `try_map_coords`

https://rust-lang.github.io/rfcs/1940-must-use-functions.html

So the user doesn't forget to check the result of the operations

**Comment by lnicola** [comment]
Doesn't the `#[must_use]` on `Result` do the same thing?

**Comment by frewsxcv** [comment]
Ooops you're right. Just noticed that. Good catch!
