### ISSUE TITLE
Deprecate `geo::algorithm::proj`?

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#723]
With the introduction of the `Transform` algorithm, do we need to expose the `proj` module and crate anymore?

**Comment by lnicola** [comment]
Sounds, reasonable, it's just a set of re-exports:

```rust
pub use proj::{Area, Coord, Info, Proj, ProjBuilder, ProjError, Projinfo};
```

**Comment by michaelkirk** [comment]
The re-exports are kind of nice because then you don't need to worry about explicitly including proj in your Cargo.toml, and in particular, you don't have to worry about mismatched versions.

I'd vote to keep it.
