### ISSUE TITLE
Version 0.7.4 of geo-types breaks semver compatibility

### ISSUE THREAD

**Issue by funbringer** [georust/geo#808]
One may argue that changing rust edition in a [patch update](https://semver.org/#summary) breaks semver compatibility, because it forces the user to update their toolchain (for the record, `edition = 2021` first appeared in rust 1.56). I don't know if you actually follow semver convention, but the previous version (0.7.3) of geo-types used [2018 edition](https://github.com/georust/geo/blob/1e5b15cf64f5e3248d64b2573ac80e2aaaf8ab39/geo-types/Cargo.toml#L11), which means that the sudden transition to 2021 edition instantly breaks MSRV guarantees of any crate with `geo-types = 0.7`, e.g. [`tokio-postgres`](https://github.com/sfackler/rust-postgres/blob/38da7fa8fe0067f47b60c147ccdaa214ab5f5211/tokio-postgres/Cargo.toml#L69).

Please see https://github.com/sfackler/rust-postgres/issues/885 for more details.

**Comment by michaelkirk** [comment]
Hi @funbringer - Like many other crates, we don't consider raising our MSRV as semver breaking. 

So as not to rehash the will trodden space of this discussion, here's some existing conversation around it: 
https://users.rust-lang.org/t/rust-version-requirement-change-as-semver-breaking-or-not/20980/4

**Comment by funbringer** [comment]
Okay, thanks for the reply anyway.
