### ISSUE TITLE
Create `Union` algorithm trait

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#81]
![](https://www.mathworks.com/help/map/polybool.png)

Similar to https://github.com/georust/rust-geo/issues/80

**Comment by acfoltzer** [comment]
Would this be a good issue for a new contributor to work on? I could really use polygon union for one of my projects, though I'd have to study up on potential algorithms.

**Comment by urschrei** [comment]
@acfoltzer Absolutely! Some ideas have already been kicked around in #80. In short, it requires a lot of other things to be in place – the implementation of the binary search tree (Bentley-Ottmann needs a tree that can update its sweepline value, see https://github.com/ideasman42/isect_segments-bentley_ottmann/issues/10) and priority queue that @shterrett refers to remain open questions, though as I mention there's now an excellent DCEL implementation available in Spade. Progress on any aspect of this would be great. It's also worth looking at the clipping crate, depending on what kind of polygons you're working with. It's less general, but may be suitable for your use case.

**Comment by urschrei** [comment]
Closed by #835!
