### ISSUE TITLE
periodic maintenance. Bump version of approx from 0.4.0 to 0.51

### ISSUE THREAD

**Issue by martinfrances107** [georust/geo#849]
I know this is a contraversial topic, so I am going to tread lightly, because I know other have different perspectives. I am raising this as an issue just to I can get a sense of maintainers and other contributors views.

I am a minor contributer here, but I also have a project that relies on this project, so I going to start off speaking as maintainer of a upstream project.

Upstream:  I periodically run cargo-outdated, for secuirty and so I can de-risk the techinical debt of a subpackage making radical changes to the API on me.

With a complex set of sub-dependancies 'Cargo outdated' generates a lot of information which has to be reasonded  with and then  filtered out.

I am seeing that if I can bump the version of approx  as stated in the title. then it would quell the noise from cargo outdated.

I am about to submit a PR with the changes to all the Cargo.toml filles bumping the minor version number

There are other subpackages that are slowly getting outdated. Depending on how to community feels ... I will submit PR to slowly bring everything upto date.

**Comment by michaelkirk** [comment]
Fixed in #850
