### ISSUE TITLE
Geodesic Distance in Eastern Hemisphere

### ISSUE THREAD

**Issue by pedrobmorales** [georust/geo#900]
Hello Geo team,

It appears that the geodesic distance in the Eastern Hemisphere produces NaN.  I have included the attached unit test.
In the test case below, 2.0 isn't the correct distance, but I was just using this to test the output.

```
    #[test]
    fn why_return_nan3() {
        use geo::{point, coord, prelude::*};

        let p1 = point!(x: 26.2937008, y: 121.5456626);
        let p2 = point!(x: 26.0175862, y: 121.2261787);

        let distance1 = p1.geodesic_distance(&p2);
        let distance2 = p2.geodesic_distance(&p1);
        // assert_eq!(distance2, distance1);
        assert_eq!(2.0, distance2);
    }
```

**Comment by lnicola** [comment]
Yeah, it's 44228.9 with them reversed.

**Comment by pedrobmorales** [comment]
Awesome, yes!! Thank you so much!  I confirm that I get the same values.
