### ISSUE TITLE
Convex hull of three colinear points contains all three points

### ISSUE THREAD

**Issue by Tyilo** [georust/geo#905]
When calculating the convex hull of `(0, 0)`, `(1, 1)` and `(2, 2)`, the result contains `(1, 1)` even though it should not.

This is also inconsistent with computing the convex hull for `n > 3` colinear points, which only contains the two endpoints, which can be tested with the following code:
```rust
use geo::geometry::*;
use geo::{point, ConvexHull};

fn hull_size(n: usize) -> usize {
    let points: Vec<_> = (0..n as isize).map(|i| point!(x: i, y: i)).collect();
    let mp = MultiPoint::new(points);

    let hull = mp.convex_hull();
    hull.exterior().0.len()
}

fn main() {
    for i in 0..10 {
        println!("{}: {}", i, hull_size(i));
    }
}
```

When running this with `geo` v0.23.0 the output is:
```
0: 0
1: 2
2: 3
3: 4
4: 3
5: 3
6: 3
7: 3
8: 3
9: 3
```

`3: 3` is the expected output instead of `3: 4`.

**Comment by rmanoka** [comment]
I'm not sure we guarantee the strict convexity in the quick-hull impl.  Can you try the [graham_hull](https://docs.rs/geo/latest/geo/algorithm/convex_hull/graham/fn.graham_hull.html) implementation where you can specifically pass the flag?

**Comment by Tyilo** [comment]
It doesn't work with `graham_hull` either.
The following code:
```rust
use geo::geometry::*;
use geo::{point, ConvexHull};

fn hull_size(n: usize) -> usize {
    let points: Vec<_> = (0..n as isize).map(|i| point!(x: i, y: i)).collect();
    let mp = MultiPoint::new(points);

    let hull = mp.convex_hull();
    hull.exterior().0.len()
}

fn hull_size_graham(n: usize, include_on_hull: bool) -> usize {
    let mut coords: Vec<_> = (0..n as isize).map(|i| Coordinate { x: i, y: i }).collect();
    let hull = geo::algorithm::convex_hull::graham_hull(&mut coords, include_on_hull);

    hull.0.len()
}

fn main() {
    for i in 0..10 {
        println!("{}: {} {} {}", i, hull_size(i), hull_size_graham(i, false), hull_size_graham(i, true));
    }
}
```

produces

```
0: 0 0 0
1: 2 2 2
2: 3 3 3
3: 4 4 4
4: 3 3 5
5: 3 3 6
6: 3 3 7
7: 3 3 8
8: 3 3 9
9: 3 3 10
```

where it should be `3: 3 3 4` instead.

**Comment by Tyilo** [comment]
The problem seems to be in the [`trivial_hull` implementation](https://github.com/georust/geo/blob/3aed19362ead3bf16dbe3d5c543da1cbde9ff0a8/geo/src/algorithm/convex_hull/mod.rs#L70) which is used by both the `qhull` and `graham_hull` implementations.
