### ISSUE TITLE
Use SPDX license expression

### ISSUE THREAD

**Issue by gerritsangel** [georust/geo#927]
I tried to generate a SBOM with the CycloneDX cargo plugin. Unfortunately it fails with the following error:

> Package geo has an invalid license expression, trying lax parsing (MIT/Apache-2.0): Invalid SPDX expression: invalid character(s)

Apparently, the license parameter in the Cargo.toml must be 

```toml
license = "MIT OR Apache-2.0"
```

(See also the [Cargo docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields)).

If there is interest, I can open a PR :)

**Comment by lnicola** [comment]
Yes, please do.

**Comment by gerritsangel** [comment]
Merged in https://github.com/georust/geo/pull/928.
