### ISSUE TITLE
Signed and Unsigned Area

### ISSUE THREAD

**Issue by xlqian** [georust/geo#93]
Area returned by current algorithm is signed, which may lead to confusing usage. 

Here is what we'd like to propose for enhancement : 

- implement `UnsingedArea` 
- Complete the doc

**Comment by frewsxcv** [comment]
Seems like a good idea to me :+1:

**Comment by TeXitoi** [comment]
I think `SignedArea` and `Area` are better, even if that's quite a big API change that may be silent in an upgrade.

**Comment by frewsxcv** [comment]
Done in https://github.com/georust/geo/pull/463
