### ISSUE TITLE
Add "Geospatial" category to `Cargo.toml`

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#974]
https://github.com/rust-lang/crates.io/commit/9b65b4c004c503cf234c503e82d8575ba42c45e2

https://doc.rust-lang.org/cargo/reference/manifest.html#the-categories-field

https://github.com/HydroniumLabs/h3oh3o/commit/9e584fa5a1aebbad78c76fe828d9085ddf06380e

**Comment by lnicola** [comment]
Added in #1034.
